// Generated by par/scratch/gen_daycount_oracles.py from ISDA's published workbook.
// Do not hand-edit: re-run the generator instead, so every number keeps its provenance.
// The `Oracle` type, the combined corpus and `require(_:)` live in Oracles.swift.
import Foundation

extension Oracles {
    /// The ISDA Comparison sheet's own termination date, encoded yyyyMMdd.
    /// 4.16(h) substitutes 30 for an end date on the last day of February *unless* it is this date.
    static let terminationDate: Double = 20090228

    static let isdaSource = """
        ISDA, \"Calculation examples of 30/360 and 30E/360 in the 2006 ISDA Definitions\" (30-360-2006ISDADefs.xls, Comparison sheet), https://www.isda.org/a/mIJEE/30-360-2006ISDADefs.xls - 2006 ISDA Definitions section 4.16(f)/(g)/(h); retrieved 2026-07-27
        """

    /// ISDA's 22 published date pairs. Expected numbers live ONLY here, tied to that source.
    static let isdaRows: [Oracle] = [
        Oracle(
            id: "isda-3060-2007-01-15-2007-01-30",
            source: isdaSource,
            inputs: ["start": 20070115, "end": 20070130],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 15, "d1_thirty360": 15, "d2_thirty360": 30, "days_thirtyE360": 15, "d1_thirtyE360": 15, "d2_thirtyE360": 30, "days_thirtyE360ISDA": 15, "d1_thirtyE360ISDA": 15, "d2_thirtyE360ISDA": 30, "days_actual": 15],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2007-01-15-2007-02-15",
            source: isdaSource,
            inputs: ["start": 20070115, "end": 20070215],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 30, "d1_thirty360": 15, "d2_thirty360": 15, "days_thirtyE360": 30, "d1_thirtyE360": 15, "d2_thirtyE360": 15, "days_thirtyE360ISDA": 30, "d1_thirtyE360ISDA": 15, "d2_thirtyE360ISDA": 15, "days_actual": 31],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2007-01-15-2007-07-15",
            source: isdaSource,
            inputs: ["start": 20070115, "end": 20070715],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 180, "d1_thirty360": 15, "d2_thirty360": 15, "days_thirtyE360": 180, "d1_thirtyE360": 15, "d2_thirtyE360": 15, "days_thirtyE360ISDA": 180, "d1_thirtyE360ISDA": 15, "d2_thirtyE360ISDA": 15, "days_actual": 181],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2007-09-30-2008-03-31",
            source: isdaSource,
            inputs: ["start": 20070930, "end": 20080331],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 180, "d1_thirty360": 30, "d2_thirty360": 30, "days_thirtyE360": 180, "d1_thirtyE360": 30, "d2_thirtyE360": 30, "days_thirtyE360ISDA": 180, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 30, "days_actual": 183],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2007-09-30-2007-10-31",
            source: isdaSource,
            inputs: ["start": 20070930, "end": 20071031],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 30, "d1_thirty360": 30, "d2_thirty360": 30, "days_thirtyE360": 30, "d1_thirtyE360": 30, "d2_thirtyE360": 30, "days_thirtyE360ISDA": 30, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 30, "days_actual": 31],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2007-09-30-2008-09-30",
            source: isdaSource,
            inputs: ["start": 20070930, "end": 20080930],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 360, "d1_thirty360": 30, "d2_thirty360": 30, "days_thirtyE360": 360, "d1_thirtyE360": 30, "d2_thirtyE360": 30, "days_thirtyE360ISDA": 360, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 30, "days_actual": 366],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2007-01-15-2007-01-31",
            source: isdaSource,
            inputs: ["start": 20070115, "end": 20070131],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 16, "d1_thirty360": 15, "d2_thirty360": 31, "days_thirtyE360": 15, "d1_thirtyE360": 15, "d2_thirtyE360": 30, "days_thirtyE360ISDA": 15, "d1_thirtyE360ISDA": 15, "d2_thirtyE360ISDA": 30, "days_actual": 16],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2007-01-31-2007-02-28",
            source: isdaSource,
            inputs: ["start": 20070131, "end": 20070228],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 28, "d1_thirty360": 30, "d2_thirty360": 28, "days_thirtyE360": 28, "d1_thirtyE360": 30, "d2_thirtyE360": 28, "days_thirtyE360ISDA": 30, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 30, "days_actual": 28],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2007-02-28-2007-03-31",
            source: isdaSource,
            inputs: ["start": 20070228, "end": 20070331],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 33, "d1_thirty360": 28, "d2_thirty360": 31, "days_thirtyE360": 32, "d1_thirtyE360": 28, "d2_thirtyE360": 30, "days_thirtyE360ISDA": 30, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 30, "days_actual": 31],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2006-08-31-2007-02-28",
            source: isdaSource,
            inputs: ["start": 20060831, "end": 20070228],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 178, "d1_thirty360": 30, "d2_thirty360": 28, "days_thirtyE360": 178, "d1_thirtyE360": 30, "d2_thirtyE360": 28, "days_thirtyE360ISDA": 180, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 30, "days_actual": 181],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2007-02-28-2007-08-31",
            source: isdaSource,
            inputs: ["start": 20070228, "end": 20070831],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 183, "d1_thirty360": 28, "d2_thirty360": 31, "days_thirtyE360": 182, "d1_thirtyE360": 28, "d2_thirtyE360": 30, "days_thirtyE360ISDA": 180, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 30, "days_actual": 184],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2007-02-14-2007-02-28",
            source: isdaSource,
            inputs: ["start": 20070214, "end": 20070228],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 14, "d1_thirty360": 14, "d2_thirty360": 28, "days_thirtyE360": 14, "d1_thirtyE360": 14, "d2_thirtyE360": 28, "days_thirtyE360ISDA": 16, "d1_thirtyE360ISDA": 14, "d2_thirtyE360ISDA": 30, "days_actual": 14],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2007-02-26-2008-02-29",
            source: isdaSource,
            inputs: ["start": 20070226, "end": 20080229],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 363, "d1_thirty360": 26, "d2_thirty360": 29, "days_thirtyE360": 363, "d1_thirtyE360": 26, "d2_thirtyE360": 29, "days_thirtyE360ISDA": 364, "d1_thirtyE360ISDA": 26, "d2_thirtyE360ISDA": 30, "days_actual": 368],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2008-02-29-2009-02-28",
            source: isdaSource,
            inputs: ["start": 20080229, "end": 20090228],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 359, "d1_thirty360": 29, "d2_thirty360": 28, "days_thirtyE360": 359, "d1_thirtyE360": 29, "d2_thirtyE360": 28, "days_thirtyE360ISDA": 358, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 28, "days_actual": 365],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2008-02-29-2008-03-30",
            source: isdaSource,
            inputs: ["start": 20080229, "end": 20080330],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 31, "d1_thirty360": 29, "d2_thirty360": 30, "days_thirtyE360": 31, "d1_thirtyE360": 29, "d2_thirtyE360": 30, "days_thirtyE360ISDA": 30, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 30, "days_actual": 30],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2008-02-29-2008-03-31",
            source: isdaSource,
            inputs: ["start": 20080229, "end": 20080331],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 32, "d1_thirty360": 29, "d2_thirty360": 31, "days_thirtyE360": 31, "d1_thirtyE360": 29, "d2_thirtyE360": 30, "days_thirtyE360ISDA": 30, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 30, "days_actual": 31],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2007-02-28-2007-03-05",
            source: isdaSource,
            inputs: ["start": 20070228, "end": 20070305],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 7, "d1_thirty360": 28, "d2_thirty360": 5, "days_thirtyE360": 7, "d1_thirtyE360": 28, "d2_thirtyE360": 5, "days_thirtyE360ISDA": 5, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 5, "days_actual": 5],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2007-10-31-2007-11-28",
            source: isdaSource,
            inputs: ["start": 20071031, "end": 20071128],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 28, "d1_thirty360": 30, "d2_thirty360": 28, "days_thirtyE360": 28, "d1_thirtyE360": 30, "d2_thirtyE360": 28, "days_thirtyE360ISDA": 28, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 28, "days_actual": 28],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2007-08-31-2008-02-29",
            source: isdaSource,
            inputs: ["start": 20070831, "end": 20080229],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 179, "d1_thirty360": 30, "d2_thirty360": 29, "days_thirtyE360": 179, "d1_thirtyE360": 30, "d2_thirtyE360": 29, "days_thirtyE360ISDA": 180, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 30, "days_actual": 182],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2008-02-29-2008-08-31",
            source: isdaSource,
            inputs: ["start": 20080229, "end": 20080831],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 182, "d1_thirty360": 29, "d2_thirty360": 31, "days_thirtyE360": 181, "d1_thirtyE360": 29, "d2_thirtyE360": 30, "days_thirtyE360ISDA": 180, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 30, "days_actual": 184],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2008-08-31-2009-02-28",
            source: isdaSource,
            inputs: ["start": 20080831, "end": 20090228],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 178, "d1_thirty360": 30, "d2_thirty360": 28, "days_thirtyE360": 178, "d1_thirtyE360": 30, "d2_thirtyE360": 28, "days_thirtyE360ISDA": 178, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 28, "days_actual": 181],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
        Oracle(
            id: "isda-3060-2009-02-28-2009-08-31",
            source: isdaSource,
            inputs: ["start": 20090228, "end": 20090831],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: ["days_thirty360": 183, "d1_thirty360": 28, "d2_thirty360": 31, "days_thirtyE360": 182, "d1_thirtyE360": 28, "d2_thirtyE360": 30, "days_thirtyE360ISDA": 180, "d1_thirtyE360ISDA": 30, "d2_thirtyE360ISDA": 30, "days_actual": 184],
            tolerances: ["days_thirty360": 0, "d1_thirty360": 0, "d2_thirty360": 0, "days_thirtyE360": 0, "d1_thirtyE360": 0, "d2_thirtyE360": 0, "days_thirtyE360ISDA": 0, "d1_thirtyE360ISDA": 0, "d2_thirtyE360ISDA": 0, "days_actual": 0]
        ),
    ]
}
