// Generated by par/scratch/gen_stat_oracles.py from the NIST StRD datasets.
// Do not hand-edit: re-run the generator, so every number keeps its provenance.
// The `Oracle` type, the combined corpus and `require(_:)` live in Oracles.swift.
import Foundation

extension Oracles {
    static let norrisSource = """
        NIST/ITL Statistical Reference Datasets, Norris.dat (linear least squares, 36 observations, lower level of difficulty; Norris, J., NIST, \"Calibration of Ozone Monitors\"); https://www.itl.nist.gov/div898/strd/lls/data/LINKS/DATA/Norris.dat (US government work, public domain); retrieved 2026-07-27. Certified values computed by NIST in extended precision.
        """

    static let lewSource = """
        NIST/ITL Statistical Reference Datasets, Lew.dat (univariate summary statistics, 200 observations of steel-concrete beam deflection); https://www.itl.nist.gov/div898/strd/univ/data/Lew.dat (US government work, public domain); retrieved 2026-07-27. Certified values computed by NIST in extended precision.
        """

    /// Norris: y values, in file order.
    static let norrisY: [Double] = [0.1, 338.8, 118.1, 888.0, 9.2, 228.1, 668.5, 998.5, 449.1, 778.9, 559.2, 0.3, 0.1, 778.1, 668.8, 339.3, 448.9, 10.8, 557.7, 228.3, 998.0, 888.8, 119.6, 0.3, 0.6, 557.6, 339.3, 888.0, 998.5, 778.9, 10.2, 117.6, 228.9, 668.4, 449.2, 0.2]

    /// Norris: x values, in file order.
    static let norrisX: [Double] = [0.2, 337.4, 118.2, 884.6, 10.1, 226.5, 666.3, 996.3, 448.6, 777.0, 558.2, 0.4, 0.6, 775.5, 666.9, 338.0, 447.5, 11.6, 556.0, 228.1, 995.8, 887.6, 120.2, 0.3, 0.3, 556.8, 339.1, 887.2, 999.0, 779.0, 11.1, 118.3, 229.2, 669.1, 448.9, 0.5]

    /// Lew: 200 observations, in file order.
    static let lewValues: [Double] = [-213, -564, -35, -15, 141, 115, -420, -360, 203, -338, -431, 194, -220, -513, 154, -125, -559, 92, -21, -579, -52, 99, -543, -175, 162, -457, -346, 204, -300, -474, 164, -107, -572, -8, 83, -541, -224, 180, -420, -374, 201, -236, -531, 83, 27, -564, -112, 131, -507, -254, 199, -311, -495, 143, -46, -579, -90, 136, -472, -338, 202, -287, -477, 169, -124, -568, 17, 48, -568, -135, 162, -430, -422, 172, -74, -577, -13, 92, -534, -243, 194, -355, -465, 156, -81, -578, -64, 139, -449, -384, 193, -198, -538, 110, -44, -577, -6, 66, -552, -164, 161, -460, -344, 205, -281, -504, 134, -28, -576, -118, 156, -437, -381, 200, -220, -540, 83, 11, -568, -160, 172, -414, -408, 188, -125, -572, -32, 139, -492, -321, 205, -262, -504, 142, -83, -574, 0, 48, -571, -106, 137, -501, -266, 190, -391, -406, 194, -186, -553, 83, -13, -577, -49, 103, -515, -280, 201, 300, -506, 131, -45, -578, -80, 138, -462, -361, 201, -211, -554, 32, 74, -533, -235, 187, -372, -442, 182, -147, -566, 25, 68, -535, -244, 194, -351, -463, 174, -125, -570, 15, 72, -550, -190, 172, -424, -385, 198, -218, -536, 96]

    static let nistRows: [Oracle] = [
        Oracle(
            id: "nist-strd-norris",
            source: norrisSource,
            inputs: ["observations": 36],
            precision: "±1e-9 relative on the coefficients: NIST certifies 15 significant digits, and "
                + "a stable two-pass fit reproduces them to the limit of Double",
            values: [
                "intercept": -0.262323073774029,
                "interceptStandardDeviation": 0.232818234301152,
                "slope": 1.00211681802045,
                "slopeStandardDeviation": 0.429796848199937e-03,
                "residualStandardDeviation": 0.884796396144373,
                "rSquared": 0.999993745883712,
            ],
            tolerances: [
                "intercept": 1e-9,
                "interceptStandardDeviation": 1e-9,
                "slope": 1e-11,
                "slopeStandardDeviation": 1e-15,
                "residualStandardDeviation": 1e-9,
                "rSquared": 1e-12,
            ]
        ),
        Oracle(
            id: "nist-strd-lew",
            source: lewSource,
            inputs: ["observations": 200],
            precision: "±1e-9: NIST certifies the mean and standard deviation to 15 digits; the "
                + "autocorrelation to 15 as well",
            values: [
                "mean": -177.435000000000,
                "sampleStandardDeviation": 277.332168044316,
                "autocorrelationLag1": -0.307304800605679,
            ],
            tolerances: [
                "mean": 1e-9,
                "sampleStandardDeviation": 1e-9,
                "autocorrelationLag1": 1e-12,
            ]
        ),
    ]
}
