// Generated by par/scratch/gen_dep_oracles.py from the extracted IRS tables.
// Do not hand-edit: re-run the generator, so every number keeps its provenance.
// The `Oracle` type, the combined corpus and `require(_:)` live in Oracles.swift.
import Foundation

extension Oracles {
    /// IRS Publication 946 (2025) Appendix A, Tables A-1 through A-5: the MACRS GDS recovery
    /// percentages for every recovery period under every placed-in-service convention.
    /// Values are percent of unadjusted basis, keyed `year<n>`; tolerances are 0 because these are
    /// exact published figures and `Rounding.irsTable` reproduces them exactly.
    static let macrsRows: [Oracle] = [
        Oracle(
            id: "irs946-2025-tableA1-3yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-1 (Half-Year Convention), p. 70; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 3, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 33.33, "year2": 44.45, "year3": 14.81, "year4": 7.41],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA1-5yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-1 (Half-Year Convention), p. 70; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 5, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 20.00, "year2": 32.00, "year3": 19.20, "year4": 11.52, "year5": 11.52, "year6": 5.76],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA1-7yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-1 (Half-Year Convention), p. 70; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 7, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 14.29, "year2": 24.49, "year3": 17.49, "year4": 12.49, "year5": 8.93, "year6": 8.92, "year7": 8.93, "year8": 4.46],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA1-10yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-1 (Half-Year Convention), p. 70; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 10, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 10.00, "year2": 18.00, "year3": 14.40, "year4": 11.52, "year5": 9.22, "year6": 7.37, "year7": 6.55, "year8": 6.55, "year9": 6.56, "year10": 6.55, "year11": 3.28],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0, "year9": 0, "year10": 0, "year11": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA1-15yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-1 (Half-Year Convention), p. 70; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 15, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 5.00, "year2": 9.50, "year3": 8.55, "year4": 7.70, "year5": 6.93, "year6": 6.23, "year7": 5.90, "year8": 5.90, "year9": 5.91, "year10": 5.90, "year11": 5.91, "year12": 5.90, "year13": 5.91, "year14": 5.90, "year15": 5.91, "year16": 2.95],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0, "year9": 0, "year10": 0, "year11": 0, "year12": 0, "year13": 0, "year14": 0, "year15": 0, "year16": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA1-20yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-1 (Half-Year Convention), p. 70; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 20, "decimals": 3],
            precision: "exact - the published percentages carry 3 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 3.750, "year2": 7.219, "year3": 6.677, "year4": 6.177, "year5": 5.713, "year6": 5.285, "year7": 4.888, "year8": 4.522, "year9": 4.462, "year10": 4.461, "year11": 4.462, "year12": 4.461, "year13": 4.462, "year14": 4.461, "year15": 4.462, "year16": 4.461, "year17": 4.462, "year18": 4.461, "year19": 4.462, "year20": 4.461, "year21": 2.231],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0, "year9": 0, "year10": 0, "year11": 0, "year12": 0, "year13": 0, "year14": 0, "year15": 0, "year16": 0, "year17": 0, "year18": 0, "year19": 0, "year20": 0, "year21": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA2-3yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-2 (Mid-Quarter Convention, Placed in Service in First Quarter), pp. 70-71; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 3, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 58.33, "year2": 27.78, "year3": 12.35, "year4": 1.54],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA2-5yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-2 (Mid-Quarter Convention, Placed in Service in First Quarter), pp. 70-71; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 5, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 35.00, "year2": 26.00, "year3": 15.60, "year4": 11.01, "year5": 11.01, "year6": 1.38],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA2-7yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-2 (Mid-Quarter Convention, Placed in Service in First Quarter), pp. 70-71; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 7, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 25.00, "year2": 21.43, "year3": 15.31, "year4": 10.93, "year5": 8.75, "year6": 8.74, "year7": 8.75, "year8": 1.09],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA2-10yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-2 (Mid-Quarter Convention, Placed in Service in First Quarter), pp. 70-71; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 10, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 17.50, "year2": 16.50, "year3": 13.20, "year4": 10.56, "year5": 8.45, "year6": 6.76, "year7": 6.55, "year8": 6.55, "year9": 6.56, "year10": 6.55, "year11": 0.82],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0, "year9": 0, "year10": 0, "year11": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA2-15yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-2 (Mid-Quarter Convention, Placed in Service in First Quarter), pp. 70-71; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 15, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 8.75, "year2": 9.13, "year3": 8.21, "year4": 7.39, "year5": 6.65, "year6": 5.99, "year7": 5.90, "year8": 5.91, "year9": 5.90, "year10": 5.91, "year11": 5.90, "year12": 5.91, "year13": 5.90, "year14": 5.91, "year15": 5.90, "year16": 0.74],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0, "year9": 0, "year10": 0, "year11": 0, "year12": 0, "year13": 0, "year14": 0, "year15": 0, "year16": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA2-20yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-2 (Mid-Quarter Convention, Placed in Service in First Quarter), pp. 70-71; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 20, "decimals": 3],
            precision: "exact - the published percentages carry 3 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 6.563, "year2": 7.000, "year3": 6.482, "year4": 5.996, "year5": 5.546, "year6": 5.130, "year7": 4.746, "year8": 4.459, "year9": 4.459, "year10": 4.459, "year11": 4.459, "year12": 4.460, "year13": 4.459, "year14": 4.460, "year15": 4.459, "year16": 4.460, "year17": 4.459, "year18": 4.460, "year19": 4.459, "year20": 4.460, "year21": 0.565],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0, "year9": 0, "year10": 0, "year11": 0, "year12": 0, "year13": 0, "year14": 0, "year15": 0, "year16": 0, "year17": 0, "year18": 0, "year19": 0, "year20": 0, "year21": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA3-3yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-3 (Mid-Quarter Convention, Placed in Service in Second Quarter), p. 72; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 3, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 41.67, "year2": 38.89, "year3": 14.14, "year4": 5.30],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA3-5yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-3 (Mid-Quarter Convention, Placed in Service in Second Quarter), p. 72; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 5, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 25.00, "year2": 30.00, "year3": 18.00, "year4": 11.37, "year5": 11.37, "year6": 4.26],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA3-7yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-3 (Mid-Quarter Convention, Placed in Service in Second Quarter), p. 72; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 7, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 17.85, "year2": 23.47, "year3": 16.76, "year4": 11.97, "year5": 8.87, "year6": 8.87, "year7": 8.87, "year8": 3.34],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA3-10yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-3 (Mid-Quarter Convention, Placed in Service in Second Quarter), p. 72; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 10, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 12.50, "year2": 17.50, "year3": 14.00, "year4": 11.20, "year5": 8.96, "year6": 7.17, "year7": 6.55, "year8": 6.55, "year9": 6.56, "year10": 6.55, "year11": 2.46],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0, "year9": 0, "year10": 0, "year11": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA3-15yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-3 (Mid-Quarter Convention, Placed in Service in Second Quarter), p. 72; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 15, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 6.25, "year2": 9.38, "year3": 8.44, "year4": 7.59, "year5": 6.83, "year6": 6.15, "year7": 5.91, "year8": 5.90, "year9": 5.91, "year10": 5.90, "year11": 5.91, "year12": 5.90, "year13": 5.91, "year14": 5.90, "year15": 5.91, "year16": 2.21],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0, "year9": 0, "year10": 0, "year11": 0, "year12": 0, "year13": 0, "year14": 0, "year15": 0, "year16": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA3-20yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-3 (Mid-Quarter Convention, Placed in Service in Second Quarter), p. 72; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 20, "decimals": 3],
            precision: "exact - the published percentages carry 3 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 4.688, "year2": 7.148, "year3": 6.612, "year4": 6.116, "year5": 5.658, "year6": 5.233, "year7": 4.841, "year8": 4.478, "year9": 4.463, "year10": 4.463, "year11": 4.463, "year12": 4.463, "year13": 4.463, "year14": 4.463, "year15": 4.462, "year16": 4.463, "year17": 4.462, "year18": 4.463, "year19": 4.462, "year20": 4.463, "year21": 1.673],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0, "year9": 0, "year10": 0, "year11": 0, "year12": 0, "year13": 0, "year14": 0, "year15": 0, "year16": 0, "year17": 0, "year18": 0, "year19": 0, "year20": 0, "year21": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA4-3yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-4 (Mid-Quarter Convention, Placed in Service in Third Quarter), p. 72; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 3, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 25.00, "year2": 50.00, "year3": 16.67, "year4": 8.33],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA4-5yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-4 (Mid-Quarter Convention, Placed in Service in Third Quarter), p. 72; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 5, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 15.00, "year2": 34.00, "year3": 20.40, "year4": 12.24, "year5": 11.30, "year6": 7.06],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA4-7yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-4 (Mid-Quarter Convention, Placed in Service in Third Quarter), p. 72; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 7, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 10.71, "year2": 25.51, "year3": 18.22, "year4": 13.02, "year5": 9.30, "year6": 8.85, "year7": 8.86, "year8": 5.53],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA4-10yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-4 (Mid-Quarter Convention, Placed in Service in Third Quarter), p. 72; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 10, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 7.50, "year2": 18.50, "year3": 14.80, "year4": 11.84, "year5": 9.47, "year6": 7.58, "year7": 6.55, "year8": 6.55, "year9": 6.56, "year10": 6.55, "year11": 4.10],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0, "year9": 0, "year10": 0, "year11": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA4-15yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-4 (Mid-Quarter Convention, Placed in Service in Third Quarter), p. 72; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 15, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 3.75, "year2": 9.63, "year3": 8.66, "year4": 7.80, "year5": 7.02, "year6": 6.31, "year7": 5.90, "year8": 5.90, "year9": 5.91, "year10": 5.90, "year11": 5.91, "year12": 5.90, "year13": 5.91, "year14": 5.90, "year15": 5.91, "year16": 3.69],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0, "year9": 0, "year10": 0, "year11": 0, "year12": 0, "year13": 0, "year14": 0, "year15": 0, "year16": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA4-20yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-4 (Mid-Quarter Convention, Placed in Service in Third Quarter), p. 72; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 20, "decimals": 3],
            precision: "exact - the published percentages carry 3 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 2.813, "year2": 7.289, "year3": 6.742, "year4": 6.237, "year5": 5.769, "year6": 5.336, "year7": 4.936, "year8": 4.566, "year9": 4.460, "year10": 4.460, "year11": 4.460, "year12": 4.460, "year13": 4.461, "year14": 4.460, "year15": 4.461, "year16": 4.460, "year17": 4.461, "year18": 4.460, "year19": 4.461, "year20": 4.460, "year21": 2.788],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0, "year9": 0, "year10": 0, "year11": 0, "year12": 0, "year13": 0, "year14": 0, "year15": 0, "year16": 0, "year17": 0, "year18": 0, "year19": 0, "year20": 0, "year21": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA5-3yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-5 (Mid-Quarter Convention, Placed in Service in Fourth Quarter), p. 73; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 3, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 8.33, "year2": 61.11, "year3": 20.37, "year4": 10.19],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA5-5yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-5 (Mid-Quarter Convention, Placed in Service in Fourth Quarter), p. 73; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 5, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 5.00, "year2": 38.00, "year3": 22.80, "year4": 13.68, "year5": 10.94, "year6": 9.58],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA5-7yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-5 (Mid-Quarter Convention, Placed in Service in Fourth Quarter), p. 73; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 7, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 3.57, "year2": 27.55, "year3": 19.68, "year4": 14.06, "year5": 10.04, "year6": 8.73, "year7": 8.73, "year8": 7.64],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA5-10yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-5 (Mid-Quarter Convention, Placed in Service in Fourth Quarter), p. 73; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 10, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 2.50, "year2": 19.50, "year3": 15.60, "year4": 12.48, "year5": 9.98, "year6": 7.99, "year7": 6.55, "year8": 6.55, "year9": 6.56, "year10": 6.55, "year11": 5.74],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0, "year9": 0, "year10": 0, "year11": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA5-15yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-5 (Mid-Quarter Convention, Placed in Service in Fourth Quarter), p. 73; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 15, "decimals": 2],
            precision: "exact - the published percentages carry 2 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 1.25, "year2": 9.88, "year3": 8.89, "year4": 8.00, "year5": 7.20, "year6": 6.48, "year7": 5.90, "year8": 5.90, "year9": 5.90, "year10": 5.91, "year11": 5.90, "year12": 5.91, "year13": 5.90, "year14": 5.91, "year15": 5.90, "year16": 5.17],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0, "year9": 0, "year10": 0, "year11": 0, "year12": 0, "year13": 0, "year14": 0, "year15": 0, "year16": 0]
        ),
        Oracle(
            id: "irs946-2025-tableA5-20yr",
            source: """
                IRS Publication 946 (2025), Appendix A, Table A-5 (Mid-Quarter Convention, Placed in Service in Fourth Quarter), p. 73; https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified against the rules by par/scratch/macrs.py.
                """,
            inputs: ["recoveryYears": 20, "decimals": 3],
            precision: "exact - the published percentages carry 3 decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: ["year1": 0.938, "year2": 7.430, "year3": 6.872, "year4": 6.357, "year5": 5.880, "year6": 5.439, "year7": 5.031, "year8": 4.654, "year9": 4.458, "year10": 4.458, "year11": 4.458, "year12": 4.458, "year13": 4.458, "year14": 4.458, "year15": 4.458, "year16": 4.458, "year17": 4.458, "year18": 4.459, "year19": 4.458, "year20": 4.459, "year21": 3.901],
            tolerances: ["year1": 0, "year2": 0, "year3": 0, "year4": 0, "year5": 0, "year6": 0, "year7": 0, "year8": 0, "year9": 0, "year10": 0, "year11": 0, "year12": 0, "year13": 0, "year14": 0, "year15": 0, "year16": 0, "year17": 0, "year18": 0, "year19": 0, "year20": 0, "year21": 0]
        ),
    ]
}
