// GENERATED by scratch/make_station_catalog.py -- do not hand-edit.
//
// Verbatim NOAA CO-OPS harmonic constants and datums (U.S. Government work, public
// domain), retrieved 2026-07-26 from https://api.tidesandcurrents.noaa.gov
//
// This is the app's OFFLINE data layer. The Kits are deliberately data-free and
// network-free; the app carries the constants so predictions work with no signal.
// Accuracy of each station is bounded by its published constituent set -- see the
// MODEL CAVEAT on `Harmonics`.
import Foundation
import TidesKit

/// A tide station's published constants, ready to build a `Station`.
struct TideStationRecord: Identifiable, Sendable {
    let id: String
    let name: String
    let region: String
    /// IANA zone of the STATION. Tide times must be read in station-local time —
    /// showing San Francisco tides in the device's time zone is a navigational error,
    /// not a formatting preference.
    let timeZoneIdentifier: String
    let latitude: Double
    let longitude: Double
    /// Z0 = MSL - MLLW, metres and feet respectively.
    let z0Meters: Double
    let z0Feet: Double
    /// "NAME,amplitude,phaseGMT" per line.
    let constituentsMetric: String
    let constituentsFeet: String

    var timeZone: TimeZone { TimeZone(identifier: timeZoneIdentifier) ?? .gmt }

    func station(unit: TideUnit) -> Station {
        Station(id: id, name: name,
                latitudeDeg: latitude, longitudeDeg: longitude,
                unit: unit,
                meanWaterLevel: unit == .meters ? z0Meters : z0Feet,
                constituents: StationCatalog.parse(
                    unit == .meters ? constituentsMetric : constituentsFeet))
    }
}

/// A current station's published constants.
struct CurrentStationRecord: Identifiable, Sendable {
    let id: String
    let bin: Int
    let name: String
    let region: String
    /// IANA zone of the station — see `TideStationRecord.timeZoneIdentifier`.
    let timeZoneIdentifier: String
    let latitude: Double
    let longitude: Double
    let meanFloodDirectionDeg: Double
    let meanEbbDirectionDeg: Double
    /// NOAA's published `majorMeanSpeed` — the station's non-tidal mean flow, cm/s.
    let meanFlowCMS: Double
    /// "NAME,majorAmplitude(cm/s),majorPhaseGMT" per line.
    let constituents: String

    var stationKey: String { "\(id)#\(bin)" }

    var timeZone: TimeZone { TimeZone(identifier: timeZoneIdentifier) ?? .gmt }

    func station() -> CurrentStation {
        CurrentStation(id: id, name: name, bin: bin,
                       meanFloodDirectionDeg: meanFloodDirectionDeg,
                       meanEbbDirectionDeg: meanEbbDirectionDeg,
                       meanFlowCMS: meanFlowCMS,
                       constituents: StationCatalog.parse(constituents))
    }
}

enum StationCatalog {

    /// Parse the embedded "NAME,amplitude,phase" table. Unknown names are skipped
    /// rather than guessed -- `Constituent(name:)` returns nil for anything the
    /// Kit does not define.
    static func parse(_ csv: String) -> [Constituent] {
        csv.split(separator: "\n").compactMap { line in
            let p = line.split(separator: ",", omittingEmptySubsequences: false)
            guard p.count == 3, let a = Double(p[1]), let g = Double(p[2]) else { return nil }
            return Constituent(name: String(p[0]), amplitude: a, greenwichPhaseDeg: g)
        }
    }

    /// NOAA primary tide stations, spanning the US coasts and tidal regimes.
    static let tideStations: [TideStationRecord] = [
        TideStationRecord(
            id: "9414290", name: "San Francisco", region: "CA",
            timeZoneIdentifier: "America/Los_Angeles",
            latitude: 37.806305, longitude: -122.46589,
            z0Meters: 0.951, z0Feet: 3.12,
            constituentsMetric: """
M2,0.576,208.2
S2,0.137,216.2
N2,0.122,183.2
K1,0.37,225.4
M4,0.022,136.8
O1,0.23,208.4
M6,0.002,7.3
MK3,0.018,124.1
S4,0.0,0.0
MN4,0.008,112.0
NU2,0.026,189.9
S6,0.0,0.0
MU2,0.007,100.2
2N2,0.013,153.3
OO1,0.012,260.0
LAM2,0.007,214.3
S1,0.007,282.6
M1,0.011,237.5
J1,0.019,244.3
MM,0.0,0.0
SSA,0.03,272.3
SA,0.044,200.2
MSF,0.0,0.0
MF,0.015,153.1
RHO,0.009,200.0
Q1,0.041,202.4
T2,0.009,204.6
R2,0.001,126.8
2Q1,0.006,208.6
P1,0.114,222.1
2SM2,0.003,37.3
M3,0.003,37.6
L2,0.018,229.6
2MK3,0.014,92.2
K2,0.04,206.0
M8,0.001,108.5
MS4,0.01,149.0
""",
            constituentsFeet: """
M2,1.89,208.2
S2,0.45,216.2
N2,0.4,183.2
K1,1.21,225.4
M4,0.07,136.8
O1,0.75,208.4
M6,0.01,7.3
MK3,0.06,124.1
S4,0.0,0.0
MN4,0.03,112.0
NU2,0.09,189.9
S6,0.0,0.0
MU2,0.02,100.2
2N2,0.04,153.3
OO1,0.04,260.0
LAM2,0.02,214.3
S1,0.02,282.6
M1,0.04,237.5
J1,0.06,244.3
MM,0.0,0.0
SSA,0.1,272.3
SA,0.14,200.2
MSF,0.0,0.0
MF,0.05,153.1
RHO,0.03,200.0
Q1,0.13,202.4
T2,0.03,204.6
R2,0.0,126.8
2Q1,0.02,208.6
P1,0.37,222.1
2SM2,0.01,37.3
M3,0.01,37.6
L2,0.06,229.6
2MK3,0.05,92.2
K2,0.13,206.0
M8,0.0,108.5
MS4,0.03,149.0
"""),
        TideStationRecord(
            id: "9410170", name: "San Diego", region: "CA",
            timeZoneIdentifier: "America/Los_Angeles",
            latitude: 32.715557, longitude: -117.17667,
            z0Meters: 0.897, z0Feet: 2.94,
            constituentsMetric: """
M2,0.542,143.3
S2,0.225,140.4
N2,0.126,123.1
K1,0.337,208.4
M4,0.003,255.5
O1,0.214,192.6
M6,0.004,62.2
MK3,0.002,215.5
S4,0.001,230.2
MN4,0.002,213.1
NU2,0.025,129.7
S6,0.001,68.1
MU2,0.015,92.0
2N2,0.016,95.4
OO1,0.011,241.9
LAM2,0.003,134.0
S1,0.005,329.0
M1,0.013,225.1
J1,0.019,220.9
MM,0.0,0.0
SSA,0.0,0.0
SA,0.076,180.5
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.008,184.9
Q1,0.039,185.4
T2,0.014,128.1
R2,0.002,155.6
2Q1,0.005,186.1
P1,0.106,205.9
2SM2,0.002,312.3
M3,0.003,356.5
L2,0.012,124.5
2MK3,0.003,192.8
K2,0.066,134.5
M8,0.0,0.0
MS4,0.002,203.2
""",
            constituentsFeet: """
M2,1.78,143.3
S2,0.74,140.4
N2,0.41,123.1
K1,1.11,208.4
M4,0.01,255.5
O1,0.7,192.6
M6,0.01,62.2
MK3,0.01,215.5
S4,0.0,230.2
MN4,0.01,213.1
NU2,0.08,129.7
S6,0.0,68.1
MU2,0.05,92.0
2N2,0.05,95.4
OO1,0.04,241.9
LAM2,0.01,134.0
S1,0.02,329.0
M1,0.04,225.1
J1,0.06,220.9
MM,0.0,0.0
SSA,0.0,0.0
SA,0.25,180.5
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.03,184.9
Q1,0.13,185.4
T2,0.05,128.1
R2,0.01,155.6
2Q1,0.02,186.1
P1,0.35,205.9
2SM2,0.01,312.3
M3,0.01,356.5
L2,0.04,124.5
2MK3,0.01,192.8
K2,0.22,134.5
M8,0.0,0.0
MS4,0.01,203.2
"""),
        TideStationRecord(
            id: "9447130", name: "Seattle", region: "WA",
            timeZoneIdentifier: "America/Los_Angeles",
            latitude: 47.60264, longitude: -122.3393,
            z0Meters: 2.024, z0Feet: 6.64,
            constituentsMetric: """
M2,1.063,10.8
S2,0.268,36.8
N2,0.214,341.1
K1,0.834,276.8
M4,0.021,200.7
O1,0.459,254.6
M6,0.009,312.8
MK3,0.036,79.3
S4,0.002,254.3
MN4,0.009,172.7
NU2,0.044,355.5
S6,0.0,0.0
MU2,0.034,238.9
2N2,0.023,313.1
OO1,0.031,330.2
LAM2,0.02,49.9
S1,0.021,45.0
M1,0.024,304.1
J1,0.043,313.4
MM,0.0,0.0
SSA,0.024,217.0
SA,0.07,283.2
MSF,0.0,0.0
MF,0.015,157.0
RHO,0.015,245.0
Q1,0.073,248.9
T2,0.016,38.0
R2,0.003,11.2
2Q1,0.01,265.5
P1,0.257,276.2
2SM2,0.008,284.4
M3,0.004,178.0
L2,0.049,58.7
2MK3,0.035,48.5
K2,0.079,37.7
M8,0.001,204.4
MS4,0.012,229.3
""",
            constituentsFeet: """
M2,3.49,10.8
S2,0.88,36.8
N2,0.7,341.1
K1,2.74,276.8
M4,0.07,200.7
O1,1.51,254.6
M6,0.03,312.8
MK3,0.12,79.3
S4,0.01,254.3
MN4,0.03,172.7
NU2,0.14,355.5
S6,0.0,0.0
MU2,0.11,238.9
2N2,0.08,313.1
OO1,0.1,330.2
LAM2,0.07,49.9
S1,0.07,45.0
M1,0.08,304.1
J1,0.14,313.4
MM,0.0,0.0
SSA,0.08,217.0
SA,0.23,283.2
MSF,0.0,0.0
MF,0.05,157.0
RHO,0.05,245.0
Q1,0.24,248.9
T2,0.05,38.0
R2,0.01,11.2
2Q1,0.03,265.5
P1,0.84,276.2
2SM2,0.03,284.4
M3,0.01,178.0
L2,0.16,58.7
2MK3,0.11,48.5
K2,0.26,37.7
M8,0.0,204.4
MS4,0.04,229.3
"""),
        TideStationRecord(
            id: "9455920", name: "Anchorage", region: "AK",
            timeZoneIdentifier: "America/Anchorage",
            latitude: 61.2375, longitude: -149.8904,
            z0Meters: 5.02, z0Feet: 16.47,
            constituentsMetric: """
M2,3.505,105.2
S2,0.977,147.4
N2,0.597,79.2
K1,0.671,342.1
M4,0.271,80.7
O1,0.371,325.0
M6,0.154,18.2
MK3,0.082,8.8
S4,0.02,207.0
MN4,0.096,60.0
NU2,0.172,82.3
S6,0.002,278.4
MU2,0.212,234.0
2N2,0.057,48.1
OO1,0.018,79.3
LAM2,0.093,111.1
S1,0.003,74.2
M1,0.03,40.2
J1,0.025,65.2
MM,0.051,36.1
SSA,0.024,283.0
SA,0.096,217.4
MSF,0.135,39.6
MF,0.025,94.7
RHO,0.014,296.2
Q1,0.06,330.6
T2,0.054,128.7
R2,0.011,233.5
2Q1,0.005,328.4
P1,0.176,340.9
2SM2,0.057,348.6
M3,0.018,148.0
L2,0.211,125.2
2MK3,0.099,21.2
K2,0.271,138.1
M8,0.045,346.2
MS4,0.175,128.2
SIGMA1,0.047,24.4
MP1,0.066,67.2
CHI1,0.007,278.4
2PO1,0.018,143.0
SO1,0.074,151.1
MSN2,0.05,335.1
MNS2,0.059,201.8
OP2,0.007,100.5
MKS2,0.016,300.1
2NS2,0.009,167.2
MLN2S2,0.039,201.5
2ML2S2,0.025,43.4
SKM2,0.024,340.7
2MS2K2,0.005,245.0
MKL2S2,0.003,108.5
M2KS2,0.007,126.9
2SNMK2,0.001,137.7
2KMSN2,0.002,167.5
SO3,0.053,31.4
SK3,0.042,67.6
NO3,0.041,353.7
MK4,0.043,122.2
SN4,0.022,146.9
2MLS4,0.028,220.8
3MS4,0.037,161.2
ML4,0.028,72.6
N4,0.018,36.4
SL4,0.021,117.4
MNO5,0.019,249.7
2MO5,0.035,268.3
2MK5,0.061,256.3
MSK5,0.029,324.6
3KM5,0.01,305.5
2MP5,0.028,285.1
3MP5,0.022,357.4
MNK5,0.021,239.1
2SM6,0.027,114.6
2MN6,0.081,352.7
MSN6,0.027,48.1
2MS6,0.144,59.4
2NMLS6,0.024,297.7
2NM6,0.021,325.4
MSL6,0.033,70.2
2ML6,0.025,34.3
MSK6,0.017,91.8
2MLNS6,0.031,325.1
3MLS6,0.03,176.1
2MK6,0.038,46.7
2MNO7,0.015,245.7
2NMK7,0.004,204.4
2MSO7,0.025,293.2
MSKO7,0.031,122.5
2MSN8,0.024,14.0
3MS8,0.064,26.0
2MS8,0.023,80.3
2MN8,0.011,292.9
3MN8,0.033,319.3
2MSL8,0.02,30.1
4MLS8,0.014,128.4
3ML8,0.008,350.6
3MK8,0.014,16.8
2MSK8,0.014,62.5
2M2NK9,0.003,144.4
3MNK9,0.007,171.4
4MK9,0.009,201.2
3MSK9,0.014,244.7
4MN10,0.016,273.1
M10,0.017,299.2
3MNS10,0.02,315.2
4MS10,0.034,336.3
3MSL10,0.013,346.3
3M2S10,0.019,22.5
4MSK11,0.009,204.0
4MNS12,0.014,276.2
5MS12,0.018,298.3
4MSL12,0.008,307.0
4M2S12,0.014,343.0
TK1,0.009,352.9
RP1,0.008,322.1
KP1,0.004,324.7
THETA1,0.012,310.7
KJ2,0.005,314.9
OO2,0.025,31.0
""",
            constituentsFeet: """
M2,11.5,105.2
S2,3.21,147.4
N2,1.96,79.2
K1,2.2,342.1
M4,0.89,80.7
O1,1.22,325.0
M6,0.51,18.2
MK3,0.27,8.8
S4,0.07,207.0
MN4,0.31,60.0
NU2,0.56,82.3
S6,0.01,278.4
MU2,0.7,234.0
2N2,0.19,48.1
OO1,0.06,79.3
LAM2,0.31,111.1
S1,0.01,74.2
M1,0.1,40.2
J1,0.08,65.2
MM,0.17,36.1
SSA,0.08,283.0
SA,0.31,217.4
MSF,0.44,39.6
MF,0.08,94.7
RHO,0.05,296.2
Q1,0.2,330.6
T2,0.18,128.7
R2,0.04,233.5
2Q1,0.02,328.4
P1,0.58,340.9
2SM2,0.19,348.6
M3,0.06,148.0
L2,0.69,125.2
2MK3,0.32,21.2
K2,0.89,138.1
M8,0.15,346.2
MS4,0.57,128.2
SIGMA1,0.15,24.4
MP1,0.22,67.2
CHI1,0.02,278.4
2PO1,0.06,143.0
SO1,0.24,151.1
MSN2,0.16,335.1
MNS2,0.19,201.8
OP2,0.02,100.5
MKS2,0.05,300.1
2NS2,0.03,167.2
MLN2S2,0.13,201.5
2ML2S2,0.08,43.4
SKM2,0.08,340.7
2MS2K2,0.02,245.0
MKL2S2,0.01,108.5
M2KS2,0.02,126.9
2SNMK2,0.0,137.7
2KMSN2,0.01,167.5
SO3,0.17,31.4
SK3,0.14,67.6
NO3,0.13,353.7
MK4,0.14,122.2
SN4,0.07,146.9
2MLS4,0.09,220.8
3MS4,0.12,161.2
ML4,0.09,72.6
N4,0.06,36.4
SL4,0.07,117.4
MNO5,0.06,249.7
2MO5,0.11,268.3
2MK5,0.2,256.3
MSK5,0.1,324.6
3KM5,0.03,305.5
2MP5,0.09,285.1
3MP5,0.07,357.4
MNK5,0.07,239.1
2SM6,0.09,114.6
2MN6,0.27,352.7
MSN6,0.09,48.1
2MS6,0.47,59.4
2NMLS6,0.08,297.7
2NM6,0.07,325.4
MSL6,0.11,70.2
2ML6,0.08,34.3
MSK6,0.06,91.8
2MLNS6,0.1,325.1
3MLS6,0.1,176.1
2MK6,0.12,46.7
2MNO7,0.05,245.7
2NMK7,0.01,204.4
2MSO7,0.08,293.2
MSKO7,0.1,122.5
2MSN8,0.08,14.0
3MS8,0.21,26.0
2MS8,0.08,80.3
2MN8,0.04,292.9
3MN8,0.11,319.3
2MSL8,0.07,30.1
4MLS8,0.05,128.4
3ML8,0.03,350.6
3MK8,0.05,16.8
2MSK8,0.05,62.5
2M2NK9,0.01,144.4
3MNK9,0.02,171.4
4MK9,0.03,201.2
3MSK9,0.05,244.7
4MN10,0.05,273.1
M10,0.06,299.2
3MNS10,0.07,315.2
4MS10,0.11,336.3
3MSL10,0.04,346.3
3M2S10,0.06,22.5
4MSK11,0.03,204.0
4MNS12,0.05,276.2
5MS12,0.06,298.3
4MSL12,0.03,307.0
4M2S12,0.05,343.0
TK1,0.03,352.9
RP1,0.03,322.1
KP1,0.01,324.7
THETA1,0.04,310.7
KJ2,0.02,314.9
OO2,0.08,31.0
"""),
        TideStationRecord(
            id: "8443970", name: "Boston", region: "MA",
            timeZoneIdentifier: "America/New_York",
            latitude: 42.35389, longitude: -71.05028,
            z0Meters: 1.586, z0Feet: 5.2,
            constituentsMetric: """
M2,1.371,109.2
S2,0.208,146.2
N2,0.305,76.7
K1,0.143,205.6
M4,0.023,29.0
O1,0.116,187.1
M6,0.029,281.3
MK3,0.006,231.8
S4,0.002,119.3
MN4,0.011,13.7
NU2,0.066,84.0
S6,0.002,246.8
MU2,0.01,53.3
2N2,0.041,53.7
OO1,0.004,218.7
LAM2,0.02,140.1
S1,0.005,131.6
M1,0.005,223.2
J1,0.01,210.0
MM,0.0,0.0
SSA,0.022,97.5
SA,0.049,136.3
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.005,179.3
Q1,0.019,172.1
T2,0.018,120.1
R2,0.004,13.1
2Q1,0.002,211.3
P1,0.047,204.8
2SM2,0.003,110.3
M3,0.002,149.2
L2,0.068,160.4
2MK3,0.007,204.7
K2,0.059,146.1
M8,0.006,241.3
MS4,0.009,74.0
""",
            constituentsFeet: """
M2,4.5,109.2
S2,0.68,146.2
N2,1.0,76.7
K1,0.47,205.6
M4,0.08,29.0
O1,0.38,187.1
M6,0.1,281.3
MK3,0.02,231.8
S4,0.01,119.3
MN4,0.04,13.7
NU2,0.22,84.0
S6,0.01,246.8
MU2,0.03,53.3
2N2,0.13,53.7
OO1,0.01,218.7
LAM2,0.07,140.1
S1,0.02,131.6
M1,0.02,223.2
J1,0.03,210.0
MM,0.0,0.0
SSA,0.07,97.5
SA,0.16,136.3
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.02,179.3
Q1,0.06,172.1
T2,0.06,120.1
R2,0.01,13.1
2Q1,0.01,211.3
P1,0.15,204.8
2SM2,0.01,110.3
M3,0.01,149.2
L2,0.22,160.4
2MK3,0.02,204.7
K2,0.19,146.1
M8,0.02,241.3
MS4,0.03,74.0
"""),
        TideStationRecord(
            id: "8518750", name: "The Battery", region: "NY",
            timeZoneIdentifier: "America/New_York",
            latitude: 40.700554, longitude: -74.01417,
            z0Meters: 0.783, z0Feet: 2.57,
            constituentsMetric: """
M2,0.671,18.2
S2,0.128,42.9
N2,0.156,0.5
K1,0.103,178.5
M4,0.024,264.1
O1,0.051,176.3
M6,0.023,150.4
MK3,0.008,69.5
S4,0.011,20.8
MN4,0.011,265.9
NU2,0.026,359.7
S6,0.001,272.0
MU2,0.023,10.0
2N2,0.022,347.7
OO1,0.003,209.5
LAM2,0.008,10.5
S1,0.013,132.1
M1,0.004,247.4
J1,0.004,196.6
MM,0.0,0.0
SSA,0.032,55.3
SA,0.094,144.6
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.002,143.9
Q1,0.011,196.6
T2,0.012,32.4
R2,0.002,299.9
2Q1,0.004,234.6
P1,0.033,178.8
2SM2,0.002,357.9
M3,0.01,66.1
L2,0.023,21.0
2MK3,0.006,44.7
K2,0.036,44.5
M8,0.002,332.2
MS4,0.015,258.9
""",
            constituentsFeet: """
M2,2.2,18.2
S2,0.42,42.9
N2,0.51,0.5
K1,0.34,178.5
M4,0.08,264.1
O1,0.17,176.3
M6,0.08,150.4
MK3,0.03,69.5
S4,0.04,20.8
MN4,0.04,265.9
NU2,0.09,359.7
S6,0.0,272.0
MU2,0.08,10.0
2N2,0.07,347.7
OO1,0.01,209.5
LAM2,0.03,10.5
S1,0.04,132.1
M1,0.01,247.4
J1,0.01,196.6
MM,0.0,0.0
SSA,0.1,55.3
SA,0.31,144.6
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.01,143.9
Q1,0.04,196.6
T2,0.04,32.4
R2,0.01,299.9
2Q1,0.01,234.6
P1,0.11,178.8
2SM2,0.01,357.9
M3,0.03,66.1
L2,0.08,21.0
2MK3,0.02,44.7
K2,0.12,44.5
M8,0.01,332.2
MS4,0.05,258.9
"""),
        TideStationRecord(
            id: "8723214", name: "Virginia Key", region: "FL",
            timeZoneIdentifier: "America/New_York",
            latitude: 25.7314, longitude: -80.1618,
            z0Meters: 0.342, z0Feet: 1.13,
            constituentsMetric: """
M2,0.298,39.3
S2,0.05,70.0
N2,0.065,21.2
K1,0.032,262.5
M4,0.007,92.9
O1,0.028,290.0
M6,0.01,163.4
MK3,0.003,277.0
S4,0.001,328.7
MN4,0.002,67.8
NU2,0.013,18.4
S6,0.001,260.5
MU2,0.006,46.8
2N2,0.009,7.6
OO1,0.001,242.0
LAM2,0.004,46.5
S1,0.002,271.5
M1,0.001,316.9
J1,0.002,233.2
MM,0.0,0.0
SSA,0.064,60.5
SA,0.092,194.1
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.001,302.6
Q1,0.006,290.8
T2,0.005,55.6
R2,0.001,178.4
2Q1,0.001,264.9
P1,0.009,263.6
2SM2,0.001,39.8
M3,0.001,81.3
L2,0.012,42.3
2MK3,0.002,308.5
K2,0.014,68.2
M8,0.002,208.0
MS4,0.004,131.3
""",
            constituentsFeet: """
M2,0.98,39.3
S2,0.16,70.0
N2,0.21,21.2
K1,0.1,262.5
M4,0.02,92.9
O1,0.09,290.0
M6,0.03,163.4
MK3,0.01,277.0
S4,0.0,328.7
MN4,0.01,67.8
NU2,0.04,18.4
S6,0.0,260.5
MU2,0.02,46.8
2N2,0.03,7.6
OO1,0.0,242.0
LAM2,0.01,46.5
S1,0.01,271.5
M1,0.0,316.9
J1,0.01,233.2
MM,0.0,0.0
SSA,0.21,60.5
SA,0.3,194.1
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.0,302.6
Q1,0.02,290.8
T2,0.02,55.6
R2,0.0,178.4
2Q1,0.0,264.9
P1,0.03,263.6
2SM2,0.0,39.8
M3,0.0,81.3
L2,0.04,42.3
2MK3,0.01,308.5
K2,0.05,68.2
M8,0.01,208.0
MS4,0.01,131.3
"""),
        TideStationRecord(
            id: "8771450", name: "Galveston Pier 21", region: "TX",
            timeZoneIdentifier: "America/Chicago",
            latitude: 29.31, longitude: -94.7933,
            z0Meters: 0.252, z0Feet: 0.83,
            constituentsMetric: """
M2,0.085,293.5
S2,0.024,295.4
N2,0.022,269.5
K1,0.13,53.3
M4,0.005,256.9
O1,0.124,45.0
M6,0.001,273.5
MK3,0.001,193.8
S4,0.001,343.1
MN4,0.002,209.0
NU2,0.004,277.8
S6,0.0,0.0
MU2,0.004,227.9
2N2,0.004,224.2
OO1,0.007,82.0
LAM2,0.001,44.9
S1,0.009,326.6
M1,0.004,71.9
J1,0.006,37.2
MM,0.0,0.0
SSA,0.092,61.3
SA,0.088,154.9
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.005,39.2
Q1,0.027,26.7
T2,0.003,315.4
R2,0.001,166.3
2Q1,0.004,21.4
P1,0.038,46.8
2SM2,0.001,298.0
M3,0.001,33.3
L2,0.002,28.5
2MK3,0.001,218.2
K2,0.003,4.1
M8,0.0,0.0
MS4,0.002,265.9
""",
            constituentsFeet: """
M2,0.28,293.5
S2,0.08,295.4
N2,0.07,269.5
K1,0.43,53.3
M4,0.02,256.9
O1,0.41,45.0
M6,0.0,273.5
MK3,0.0,193.8
S4,0.0,343.1
MN4,0.01,209.0
NU2,0.01,277.8
S6,0.0,0.0
MU2,0.01,227.9
2N2,0.01,224.2
OO1,0.02,82.0
LAM2,0.0,44.9
S1,0.03,326.6
M1,0.01,71.9
J1,0.02,37.2
MM,0.0,0.0
SSA,0.3,61.3
SA,0.29,154.9
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.02,39.2
Q1,0.09,26.7
T2,0.01,315.4
R2,0.0,166.3
2Q1,0.01,21.4
P1,0.12,46.8
2SM2,0.0,298.0
M3,0.0,33.3
L2,0.01,28.5
2MK3,0.0,218.2
K2,0.01,4.1
M8,0.0,0.0
MS4,0.01,265.9
"""),
        TideStationRecord(
            id: "1612340", name: "Honolulu", region: "HI",
            timeZoneIdentifier: "Pacific/Honolulu",
            latitude: 21.303333, longitude: -157.86453,
            z0Meters: 0.251, z0Feet: 0.82,
            constituentsMetric: """
M2,0.171,59.4
S2,0.056,54.7
N2,0.033,48.8
K1,0.149,226.8
M4,0.001,195.3
O1,0.081,215.9
M6,0.001,229.7
MK3,0.001,342.6
S4,0.0,0.0
MN4,0.001,92.9
NU2,0.007,56.0
S6,0.0,0.0
MU2,0.004,7.8
2N2,0.004,39.9
OO1,0.005,251.7
LAM2,0.001,76.2
S1,0.002,210.0
M1,0.005,232.5
J1,0.01,238.3
MM,0.005,43.4
SSA,0.0,0.0
SA,0.048,177.7
MSF,0.0,0.0
MF,0.006,44.3
RHO,0.002,195.4
Q1,0.014,209.6
T2,0.004,43.6
R2,0.001,357.3
2Q1,0.001,231.0
P1,0.045,224.9
2SM2,0.001,199.8
M3,0.001,164.1
L2,0.004,49.3
2MK3,0.0,0.0
K2,0.016,45.7
M8,0.0,0.0
MS4,0.001,104.0
""",
            constituentsFeet: """
M2,0.56,59.4
S2,0.18,54.7
N2,0.11,48.8
K1,0.49,226.8
M4,0.0,195.3
O1,0.27,215.9
M6,0.0,229.7
MK3,0.0,342.6
S4,0.0,0.0
MN4,0.0,92.9
NU2,0.02,56.0
S6,0.0,0.0
MU2,0.01,7.8
2N2,0.01,39.9
OO1,0.02,251.7
LAM2,0.0,76.2
S1,0.01,210.0
M1,0.02,232.5
J1,0.03,238.3
MM,0.02,43.4
SSA,0.0,0.0
SA,0.16,177.7
MSF,0.0,0.0
MF,0.02,44.3
RHO,0.01,195.4
Q1,0.05,209.6
T2,0.01,43.6
R2,0.0,357.3
2Q1,0.0,231.0
P1,0.15,224.9
2SM2,0.0,199.8
M3,0.0,164.1
L2,0.01,49.3
2MK3,0.0,0.0
K2,0.05,45.7
M8,0.0,0.0
MS4,0.0,104.0
"""),
        TideStationRecord(
            id: "8545240", name: "Philadelphia", region: "PA",
            timeZoneIdentifier: "America/New_York",
            latitude: 39.933056, longitude: -75.14198,
            z0Meters: 1.063, z0Feet: 3.49,
            constituentsMetric: """
M2,0.826,184.2
S2,0.091,224.3
N2,0.138,166.5
K1,0.105,281.1
M4,0.083,252.5
O1,0.08,264.9
M6,0.05,246.2
MK3,0.023,331.1
S4,0.001,262.9
MN4,0.031,235.9
NU2,0.045,163.5
S6,0.0,0.0
MU2,0.043,305.5
2N2,0.015,151.2
OO1,0.005,323.0
LAM2,0.026,196.8
S1,0.018,236.5
M1,0.002,291.3
J1,0.004,340.7
MM,0.03,37.8
SSA,0.05,52.4
SA,0.112,126.7
MSF,0.029,20.6
MF,0.0,0.0
RHO,0.005,229.5
Q1,0.013,271.5
T2,0.008,211.2
R2,0.002,197.3
2Q1,0.001,221.2
P1,0.032,273.5
2SM2,0.003,105.4
M3,0.002,287.7
L2,0.092,198.9
2MK3,0.024,294.8
K2,0.03,223.0
M8,0.016,327.0
MS4,0.022,300.6
""",
            constituentsFeet: """
M2,2.71,184.2
S2,0.3,224.3
N2,0.45,166.5
K1,0.34,281.1
M4,0.27,252.5
O1,0.26,264.9
M6,0.16,246.2
MK3,0.08,331.1
S4,0.0,262.9
MN4,0.1,235.9
NU2,0.15,163.5
S6,0.0,0.0
MU2,0.14,305.5
2N2,0.05,151.2
OO1,0.02,323.0
LAM2,0.09,196.8
S1,0.06,236.5
M1,0.01,291.3
J1,0.01,340.7
MM,0.1,37.8
SSA,0.16,52.4
SA,0.37,126.7
MSF,0.1,20.6
MF,0.0,0.0
RHO,0.02,229.5
Q1,0.04,271.5
T2,0.03,211.2
R2,0.01,197.3
2Q1,0.0,221.2
P1,0.1,273.5
2SM2,0.01,105.4
M3,0.01,287.7
L2,0.3,198.9
2MK3,0.08,294.8
K2,0.1,223.0
M8,0.05,327.0
MS4,0.07,300.6
"""),
        TideStationRecord(
            id: "8656483", name: "Beaufort, Duke Marine Lab", region: "NC",
            timeZoneIdentifier: "America/New_York",
            latitude: 34.71733, longitude: -76.67066,
            z0Meters: 0.521, z0Feet: 1.71,
            constituentsMetric: """
M2,0.456,6.4
S2,0.072,30.0
N2,0.102,349.4
K1,0.082,197.8
M4,0.004,294.8
O1,0.064,205.0
M6,0.007,54.4
MK3,0.003,15.5
S4,0.006,302.3
MN4,0.003,228.6
NU2,0.02,345.6
S6,0.001,140.8
MU2,0.011,14.7
2N2,0.014,338.4
OO1,0.003,218.4
LAM2,0.006,6.7
S1,0.01,178.1
M1,0.003,222.2
J1,0.005,198.7
MM,0.0,0.0
SSA,0.051,43.7
SA,0.091,166.4
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.003,209.6
Q1,0.013,199.6
T2,0.007,15.3
R2,0.004,243.1
2Q1,0.002,187.6
P1,0.027,198.8
2SM2,0.002,28.7
M3,0.005,33.7
L2,0.02,8.0
2MK3,0.004,17.0
K2,0.02,27.3
M8,0.002,118.2
MS4,0.006,132.2
""",
            constituentsFeet: """
M2,1.5,6.4
S2,0.24,30.0
N2,0.33,349.4
K1,0.27,197.8
M4,0.01,294.8
O1,0.21,205.0
M6,0.02,54.4
MK3,0.01,15.5
S4,0.02,302.3
MN4,0.01,228.6
NU2,0.07,345.6
S6,0.0,140.8
MU2,0.04,14.7
2N2,0.05,338.4
OO1,0.01,218.4
LAM2,0.02,6.7
S1,0.03,178.1
M1,0.01,222.2
J1,0.02,198.7
MM,0.0,0.0
SSA,0.17,43.7
SA,0.3,166.4
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.01,209.6
Q1,0.04,199.6
T2,0.02,15.3
R2,0.01,243.1
2Q1,0.01,187.6
P1,0.09,198.8
2SM2,0.01,28.7
M3,0.02,33.7
L2,0.07,8.0
2MK3,0.01,17.0
K2,0.07,27.3
M8,0.01,118.2
MS4,0.02,132.2
"""),
        TideStationRecord(
            id: "8665530", name: "Charleston", region: "SC",
            timeZoneIdentifier: "America/New_York",
            latitude: 32.780834, longitude: -79.923615,
            z0Meters: 0.89, z0Feet: 2.93,
            constituentsMetric: """
M2,0.767,10.1
S2,0.116,36.0
N2,0.175,354.9
K1,0.105,198.4
M4,0.038,207.8
O1,0.079,202.0
M6,0.008,129.1
MK3,0.009,10.6
S4,0.003,333.8
MN4,0.016,198.8
NU2,0.034,351.5
S6,0.001,284.2
MU2,0.023,38.1
2N2,0.024,345.5
OO1,0.004,227.4
LAM2,0.015,358.8
S1,0.019,171.6
M1,0.005,219.1
J1,0.007,212.8
MM,0.0,0.0
SSA,0.076,49.2
SA,0.101,173.2
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.002,191.2
Q1,0.016,199.2
T2,0.013,16.8
R2,0.008,275.7
2Q1,0.001,142.7
P1,0.034,197.5
2SM2,0.002,79.4
M3,0.014,116.7
L2,0.042,3.5
2MK3,0.011,28.3
K2,0.03,36.0
M8,0.001,123.8
MS4,0.011,239.7
""",
            constituentsFeet: """
M2,2.52,10.1
S2,0.38,36.0
N2,0.57,354.9
K1,0.34,198.4
M4,0.12,207.8
O1,0.26,202.0
M6,0.03,129.1
MK3,0.03,10.6
S4,0.01,333.8
MN4,0.05,198.8
NU2,0.11,351.5
S6,0.0,284.2
MU2,0.08,38.1
2N2,0.08,345.5
OO1,0.01,227.4
LAM2,0.05,358.8
S1,0.06,171.6
M1,0.02,219.1
J1,0.02,212.8
MM,0.0,0.0
SSA,0.25,49.2
SA,0.33,173.2
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.01,191.2
Q1,0.05,199.2
T2,0.04,16.8
R2,0.03,275.7
2Q1,0.0,142.7
P1,0.11,197.5
2SM2,0.01,79.4
M3,0.05,116.7
L2,0.14,3.5
2MK3,0.04,28.3
K2,0.1,36.0
M8,0.0,123.8
MS4,0.04,239.7
"""),
    ]

    /// NOAA harmonic current stations (rectilinear, major-axis).
    static let currentStations: [CurrentStationRecord] = [
        CurrentStationRecord(
            id: "SFB1203", bin: 5, name: "Golden Gate Bridge, 0.46 nm E of", region: "",
            timeZoneIdentifier: "America/Los_Angeles",
            latitude: 37.82007, longitude: -122.473,
            meanFloodDirectionDeg: 74.0, meanEbbDirectionDeg: 235.0,
            meanFlowCMS: 25.46,
            constituents: """
M2,94.66,156.6
S2,19.75,174.6
N2,20.78,124.1
K1,25.26,155.4
M4,9.77,286.6
O1,9.57,142.9
M6,3.34,332.1
MK3,8.49,325.7
S4,0.0,0.0
MN4,4.78,262.7
S6,0.67,85.2
2N2,0.82,247.1
OO1,2.37,138.2
M1,1.65,235.1
J1,0.26,142.3
Q1,2.01,181.7
2Q1,1.8,105.7
P1,7.25,161.5
2SM2,0.72,19.9
M3,1.85,234.2
L2,4.37,176.2
2MK3,9.57,344.7
K2,7.72,169.8
M8,0.67,41.6
MS4,4.22,321.9
"""),
        CurrentStationRecord(
            id: "ACT1616", bin: 1, name: "Pollock Rip Channel (Butler Hole)", region: "",
            timeZoneIdentifier: "America/New_York",
            latitude: 41.54999923706055, longitude: -69.9832992553711,
            meanFloodDirectionDeg: 37.0, meanEbbDirectionDeg: 226.0,
            meanFlowCMS: 7.72,
            constituents: """
M2,93.53,322.3
S2,13.89,356.3
N2,15.02,282.5
K1,5.25,25.8
M4,4.12,36.2
O1,3.81,324.6
M6,2.37,81.7
MK3,0.0,0.0
S4,0.0,0.0
MN4,0.0,0.0
NU2,2.93,287.8
S6,0.0,0.0
MU2,3.6,122.9
2N2,2.01,242.6
OO1,0.0,0.0
LAM2,0.67,338.1
S1,0.0,0.0
M1,0.0,0.0
J1,0.0,0.0
MM,0.0,0.0
SSA,0.0,0.0
SA,0.0,0.0
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.0,0.0
Q1,0.72,294.0
T2,0.82,356.3
R2,0.0,0.0
2Q1,0.0,0.0
P1,1.75,25.8
2SM2,0.0,0.0
M3,0.0,0.0
L2,10.19,14.1
2MK3,0.0,0.0
K2,4.84,355.4
M8,0.0,0.0
MS4,0.0,0.0
"""),
        CurrentStationRecord(
            id: "NYH1924", bin: 1, name: "Hell Gate", region: "",
            timeZoneIdentifier: "America/New_York",
            latitude: 40.77830123901367, longitude: -73.93830108642578,
            meanFloodDirectionDeg: 50.0, meanEbbDirectionDeg: 232.0,
            meanFlowCMS: -18.31,
            constituents: """
M2,152.69,344.5
S2,21.04,7.1
N2,34.31,318.4
K1,1.39,173.5
M4,3.29,115.2
O1,3.5,114.0
M6,9.21,149.9
MK3,1.54,79.1
S4,1.39,38.0
MN4,0.77,42.0
S6,0.41,222.4
2N2,2.37,109.6
OO1,0.51,246.4
M1,0.26,144.9
J1,1.39,104.6
Q1,1.8,43.3
2Q1,0.31,352.7
P1,0.93,287.8
2SM2,1.18,264.3
M3,0.62,45.3
L2,20.89,27.0
2MK3,1.44,2.5
K2,6.64,19.3
M8,0.62,279.5
MS4,1.59,229.2
"""),
        CurrentStationRecord(
            id: "PUG1701", bin: 18, name: "Deception Pass (Narrows)", region: "",
            timeZoneIdentifier: "America/Los_Angeles",
            latitude: 48.40618896484375, longitude: -122.64311981201172,
            meanFloodDirectionDeg: 96.0, meanEbbDirectionDeg: 270.0,
            meanFlowCMS: -31.84,
            constituents: """
M2,278.72,241.2
S2,56.69,251.6
N2,55.66,219.4
K1,53.81,144.3
M4,6.53,192.0
O1,19.09,128.2
M6,20.53,202.2
MK3,7.25,171.6
S4,1.23,124.6
MN4,3.4,183.2
S6,0.0,0.0
2N2,9.62,132.4
OO1,7.97,15.2
M1,8.49,184.0
J1,4.58,204.9
Q1,4.68,161.1
2Q1,2.93,223.5
P1,17.08,192.2
2SM2,6.33,109.8
M3,4.58,89.7
L2,23.25,262.8
2MK3,13.32,191.8
M8,2.73,195.1
MS4,3.04,183.6
"""),
        CurrentStationRecord(
            id: "ACT8411", bin: 1, name: "Tampa Bay Entrance (Egmont Channel)", region: "",
            timeZoneIdentifier: "America/New_York",
            latitude: 27.604299545288086, longitude: -82.76029968261719,
            meanFloodDirectionDeg: 120.0, meanEbbDirectionDeg: 298.0,
            meanFlowCMS: 1.9,
            constituents: """
M2,53.76,122.5
S2,18.93,133.9
N2,9.62,116.1
K1,31.43,325.9
M4,2.21,304.2
O1,26.49,316.8
M6,0.0,0.0
MK3,2.16,121.3
S4,1.03,221.0
MN4,0.77,308.5
NU2,1.85,134.0
S6,0.0,0.0
MU2,2.06,345.0
2N2,1.29,109.7
OO1,1.13,334.9
LAM2,1.54,189.6
S1,4.01,44.0
M1,1.9,321.4
J1,1.54,326.8
MM,0.0,0.0
SSA,0.0,0.0
SA,0.0,0.0
MSF,0.0,0.0
MF,0.0,0.0
RHO,1.03,313.0
Q1,5.25,313.4
T2,1.13,133.9
R2,0.15,133.9
2Q1,0.67,307.9
P1,9.77,326.2
2SM2,1.54,51.1
M3,0.67,337.5
L2,2.62,150.8
2MK3,2.01,131.8
K2,7.51,136.3
M8,0.0,0.0
MS4,1.39,295.3
"""),
        CurrentStationRecord(
            id: "PCT0031", bin: 1, name: "San Diego Bay Entrance", region: "",
            timeZoneIdentifier: "America/Los_Angeles",
            latitude: 32.68170166015625, longitude: -117.2300033569336,
            meanFloodDirectionDeg: 355.0, meanEbbDirectionDeg: 173.0,
            meanFlowCMS: -4.63,
            constituents: """
M2,65.85,69.9
S2,28.55,63.6
N2,14.92,50.2
K1,20.94,131.7
M4,2.78,282.8
O1,12.96,111.0
M6,0.0,0.0
MK3,0.0,0.0
S4,0.0,0.0
MN4,0.0,0.0
NU2,2.88,52.9
S6,0.0,0.0
MU2,0.0,0.0
2N2,2.01,30.7
OO1,0.57,152.4
LAM2,0.0,0.0
S1,0.0,0.0
M1,0.93,121.5
J1,1.03,142.1
MM,0.0,0.0
SSA,0.0,0.0
SA,0.0,0.0
MSF,0.0,0.0
MF,0.0,0.0
RHO,0.0,0.0
Q1,2.52,100.6
T2,1.7,63.6
R2,0.0,0.0
2Q1,0.0,0.0
P1,6.94,131.8
2SM2,0.0,0.0
M3,0.0,0.0
L2,1.85,89.4
2MK3,0.0,0.0
K2,7.77,63.6
M8,0.0,0.0
MS4,0.0,0.0
"""),
    ]
}
