#!/usr/bin/env python3
"""Generate MarineNav/StationCatalog.swift — the app's bundled, offline station data.

The Kits stay data-free and network-free by design; the APP carries the station
constants. Everything here is verbatim NOAA CO-OPS output (U.S. Government work,
public domain) so the shipped app predicts tides and currents with no signal —
which is the whole product wedge.

Regenerate with this script; do not hand-edit the output.
"""
import json, os, hashlib, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, ".cache"); os.makedirs(CACHE, exist_ok=True)
OUT = os.path.abspath(os.path.join(HERE, "..", "MarineNav", "StationCatalog.swift"))
B = "https://api.tidesandcurrents.noaa.gov"

def get(url):
    key = os.path.join(CACHE, hashlib.sha1(url.encode()).hexdigest() + ".json")
    if os.path.exists(key):
        return json.load(open(key))
    with urllib.request.urlopen(url, timeout=180) as r:
        d = json.load(r)
    json.dump(d, open(key, "w"))
    return d

# Tide stations: a spread of regimes and coasts, all NOAA primary stations.
TIDE = ["9414290", "9410170", "9447130", "9455920", "8443970", "8518750",
        "8723214", "8771450", "1612340", "8545240", "8656483", "8665530"]

# Current stations: harmonic ("H") stations with published constants.
CURRENT = [("SFB1203", 5), ("ACT1616", 1), ("NYH1924", 1),
           ("PUG1701", 18), ("ACT8411", 1), ("PCT0031", 1)]

def meta(sid):
    return get(f"{B}/mdapi/prod/webapi/stations/{sid}.json")["stations"][0]

def harcon(sid, units):
    return get(f"{B}/mdapi/prod/webapi/stations/{sid}/harcon.json?units={units}")["HarmonicConstituents"]

def datums(sid, units):
    d = get(f"{B}/mdapi/prod/webapi/stations/{sid}/datums.json?units={units}")["datums"]
    return {x["name"]: x["value"] for x in d}

def cur_meta(sid):
    for s in get(f"{B}/mdapi/prod/webapi/stations.json?type=currentpredictions&units=metric")["stations"]:
        if s["id"] == sid:
            return s
    raise SystemExit(f"current station {sid} not found")

def cur_harcon(sid, b):
    return get(f"{B}/mdapi/prod/webapi/stations/{sid}/harcon.json"
               f"?units=metric&type=currentpredictions&bin={b}")["HarmonicConstituents"]

def cur_dirs(sid, b):
    cp = get(f"{B}/api/prod/datagetter?product=currents_predictions"
             "&application=rootyapps_catalog&begin_date=20260301&end_date=20260301"
             f"&station={sid}&bin={b}&time_zone=gmt&units=metric&interval=MAX_SLACK"
             "&format=json")["current_predictions"]["cp"]
    return cp[0].get("meanFloodDir"), cp[0].get("meanEbbDir")

def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

# NOAA publishes a standard-time abbreviation per station; tide times must be shown
# in the STATION's local time (with daylight saving), never the device's, so map to
# an IANA zone that carries the DST rules.
IANA = {
    "PST": "America/Los_Angeles",
    "MST": "America/Denver",
    "CST": "America/Chicago",
    "EST": "America/New_York",
    "AKST": "America/Anchorage",
    "HAST": "Pacific/Honolulu",
    "AST": "America/Puerto_Rico",
    "SST": "Pacific/Pago_Pago",
    "ChST": "Pacific/Guam",
}

# Current stations publish a standard-time UTC offset instead of an abbreviation.
BY_OFFSET = {-5: "America/New_York", -6: "America/Chicago", -7: "America/Denver",
             -8: "America/Los_Angeles", -9: "America/Anchorage", -10: "Pacific/Honolulu",
             -4: "America/Puerto_Rico"}

def zone(m):
    tz = m.get("timezone")
    if tz in IANA:
        return IANA[tz]
    off = m.get("timezone_offset")
    try:
        off = int(off)                      # NOAA returns this as a string for currents
    except (TypeError, ValueError):
        off = None
    if off in BY_OFFSET:
        return BY_OFFSET[off]
    raise SystemExit(f"unmapped time zone (tz={tz!r}, offset={off!r}) for {m.get('id')}")

out = ['''// GENERATED by scratch/make_station_catalog.py -- do not hand-edit.
//
// Verbatim NOAA CO-OPS harmonic constants and datums (U.S. Government work, public
// domain), retrieved 2026-07-26 from https://api.tidesandcurrents.noaa.gov
//
// This is the app's OFFLINE data layer. The Kits are deliberately data-free and
// network-free; the app carries the constants so predictions work with no signal.
// Accuracy of each station is bounded by its published constituent set -- see the
// MODEL CAVEAT on `Harmonics`.
import Foundation
import TidesKit

/// A tide station's published constants, ready to build a `Station`.
struct TideStationRecord: Identifiable, Sendable {
    let id: String
    let name: String
    let region: String
    /// IANA zone of the STATION. Tide times must be read in station-local time —
    /// showing San Francisco tides in the device's time zone is a navigational error,
    /// not a formatting preference.
    let timeZoneIdentifier: String
    let latitude: Double
    let longitude: Double
    /// Z0 = MSL - MLLW, metres and feet respectively.
    let z0Meters: Double
    let z0Feet: Double
    /// "NAME,amplitude,phaseGMT" per line.
    let constituentsMetric: String
    let constituentsFeet: String

    var timeZone: TimeZone { TimeZone(identifier: timeZoneIdentifier) ?? .gmt }

    func station(unit: TideUnit) -> Station {
        Station(id: id, name: name,
                latitudeDeg: latitude, longitudeDeg: longitude,
                unit: unit,
                meanWaterLevel: unit == .meters ? z0Meters : z0Feet,
                constituents: StationCatalog.parse(
                    unit == .meters ? constituentsMetric : constituentsFeet))
    }
}

/// A current station's published constants.
struct CurrentStationRecord: Identifiable, Sendable {
    let id: String
    let bin: Int
    let name: String
    let region: String
    /// IANA zone of the station — see `TideStationRecord.timeZoneIdentifier`.
    let timeZoneIdentifier: String
    let latitude: Double
    let longitude: Double
    let meanFloodDirectionDeg: Double
    let meanEbbDirectionDeg: Double
    /// NOAA's published `majorMeanSpeed` — the station's non-tidal mean flow, cm/s.
    let meanFlowCMS: Double
    /// "NAME,majorAmplitude(cm/s),majorPhaseGMT" per line.
    let constituents: String

    var stationKey: String { "\\(id)#\\(bin)" }

    var timeZone: TimeZone { TimeZone(identifier: timeZoneIdentifier) ?? .gmt }

    func station() -> CurrentStation {
        CurrentStation(id: id, name: name, bin: bin,
                       meanFloodDirectionDeg: meanFloodDirectionDeg,
                       meanEbbDirectionDeg: meanEbbDirectionDeg,
                       meanFlowCMS: meanFlowCMS,
                       constituents: StationCatalog.parse(constituents))
    }
}

enum StationCatalog {

    /// Parse the embedded "NAME,amplitude,phase" table. Unknown names are skipped
    /// rather than guessed -- `Constituent(name:)` returns nil for anything the
    /// Kit does not define.
    static func parse(_ csv: String) -> [Constituent] {
        csv.split(separator: "\\n").compactMap { line in
            let p = line.split(separator: ",", omittingEmptySubsequences: false)
            guard p.count == 3, let a = Double(p[1]), let g = Double(p[2]) else { return nil }
            return Constituent(name: String(p[0]), amplitude: a, greenwichPhaseDeg: g)
        }
    }

''']

# ---- tide stations ----
rows = []
for sid in TIDE:
    m = meta(sid)
    dm_, de = datums(sid, "metric"), datums(sid, "english")
    hm = "\n".join(f"{c['name']},{c['amplitude']},{c['phase_GMT']}" for c in harcon(sid, "metric"))
    he = "\n".join(f"{c['name']},{c['amplitude']},{c['phase_GMT']}" for c in harcon(sid, "english"))
    rows.append(f'''        TideStationRecord(
            id: "{sid}", name: "{esc(m['name'])}", region: "{esc(m.get('state') or '')}",
            timeZoneIdentifier: "{zone(m)}",
            latitude: {m['lat']}, longitude: {m['lng']},
            z0Meters: {round(dm_['MSL'] - dm_['MLLW'], 4)}, z0Feet: {round(de['MSL'] - de['MLLW'], 4)},
            constituentsMetric: """
{hm}
""",
            constituentsFeet: """
{he}
"""),''')
    print(f"  tide {sid} {m['name']}, {m.get('state')}")

out.append("    /// NOAA primary tide stations, spanning the US coasts and tidal regimes.\n")
out.append("    static let tideStations: [TideStationRecord] = [\n")
out.append("\n".join(rows))
out.append("\n    ]\n\n")

# ---- current stations ----
crows = []
for sid, b in CURRENT:
    m = cur_meta(sid)
    flood, ebb = cur_dirs(sid, b)
    ch = cur_harcon(sid, b)
    hc = "\n".join(f"{c['constituentName']},{c['majorAmplitude']},{c['majorPhaseGMT']}"
                   for c in ch)
    # NOAA publishes the station's non-tidal mean flow as `majorMeanSpeed`, repeated
    # on every constituent row. Omitting it shifts every velocity by that amount --
    # it is what made Golden Gate read 0.49 kn low.
    means = {c["majorMeanSpeed"] for c in ch}
    if len(means) != 1:
        raise SystemExit(f"{sid}: majorMeanSpeed is not constant: {means}")
    mean_flow = means.pop()
    crows.append(f'''        CurrentStationRecord(
            id: "{sid}", bin: {b}, name: "{esc(m['name'])}", region: "{esc(m.get('state') or '')}",
            timeZoneIdentifier: "{zone(m)}",
            latitude: {m['lat']}, longitude: {m['lng']},
            meanFloodDirectionDeg: {float(flood)}, meanEbbDirectionDeg: {float(ebb)},
            meanFlowCMS: {mean_flow},
            constituents: """
{hc}
"""),''')
    print(f"  current {sid} bin {b} {m['name']}")

out.append("    /// NOAA harmonic current stations (rectilinear, major-axis).\n")
out.append("    static let currentStations: [CurrentStationRecord] = [\n")
out.append("\n".join(crows))
out.append("\n    ]\n}\n")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write("".join(out))
print(f"\nwrote {OUT}")
