#!/usr/bin/env python3
"""Generate Tests/TidesKitTests/Fixtures.swift from cached NOAA CO-OPS responses.

Everything embedded here is verbatim NOAA output (US-gov, public domain) so that
`swift test` is green offline on a fresh clone. Regenerate with this script; do not
hand-edit the generated file.
"""
import json, os, hashlib, urllib.request, datetime as dt

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, ".cache"); os.makedirs(CACHE, exist_ok=True)
OUT = os.path.abspath(os.path.join(HERE, "..", "Kits", "Tides", "TidesKit",
                                   "Tests", "TidesKitTests", "Fixtures.swift"))

def get(url):
    key = os.path.join(CACHE, hashlib.sha1(url.encode()).hexdigest() + ".json")
    if os.path.exists(key):
        return json.load(open(key))
    with urllib.request.urlopen(url, timeout=180) as r:
        d = json.load(r)
    json.dump(d, open(key, "w"))
    return d

B = "https://api.tidesandcurrents.noaa.gov"
APP = "rootyapps_oracle_research"
D0, D1 = "20260301", "20260307"

def harcon(st, units):
    return get(f"{B}/mdapi/prod/webapi/stations/{st}/harcon.json?units={units}")["HarmonicConstituents"]

def datums(st, units):
    return {d["name"]: d["value"] for d in
            get(f"{B}/mdapi/prod/webapi/stations/{st}/datums.json?units={units}")["datums"]}

def preds(st, units, interval):
    return get(f"{B}/api/prod/datagetter?product=predictions&application={APP}"
               f"&begin_date={D0}&end_date={D1}&datum=MLLW&station={st}"
               f"&time_zone=gmt&units={units}&interval={interval}&format=json")["predictions"]

def cur_harcon(st, b):
    return get(f"{B}/mdapi/prod/webapi/stations/{st}/harcon.json"
               f"?units=metric&type=currentpredictions&bin={b}")["HarmonicConstituents"]

def cur_preds(st, b, interval="30"):
    return get(f"{B}/api/prod/datagetter?product=currents_predictions&application={APP}"
               f"&begin_date={D0}&end_date={D1}&station={st}&bin={b}"
               f"&time_zone=gmt&units=metric&interval={interval}&format=json"
               )["current_predictions"]["cp"]

def csv_cur_events(p):
    return "\n".join(f"{r['Time']},{r['Velocity_Major']},{r['Type']}" for r in p)

def swift_str(name, body, doc):
    return f"    /// {doc}\n    static let {name} = \"\"\"\n{body}\n\"\"\"\n\n"

def csv_harcon(h):
    return "\n".join(f"{c['name']},{c['amplitude']},{c['phase_GMT']}" for c in h)

def csv_pred_h(p):
    return "\n".join(f"{r['t']},{r['v']}" for r in p)

def csv_pred_hilo(p):
    return "\n".join(f"{r['t']},{r['v']},{r['type']}" for r in p)

def csv_cur_harcon(h):
    return "\n".join(f"{c['constituentName']},{c['majorAmplitude']},{c['majorPhaseGMT']}" for c in h)

def cur_mean_flow(h):
    means = {c["majorMeanSpeed"] for c in h}
    assert len(means) == 1, f"majorMeanSpeed not constant: {means}"
    return means.pop()

def csv_cur_pred(p):
    return "\n".join(f"{r['Time']},{r['Velocity_Major']}" for r in p)

parts = []
parts.append('''// GENERATED by scratch/make_fixtures.py -- do not hand-edit.
//
// Verbatim NOAA CO-OPS output (U.S. Government work, public domain), embedded so
// that `swift test` is green offline on a fresh clone. Retrieved 2026-07-26 from
// https://api.tidesandcurrents.noaa.gov -- see research/SOURCES.md.
//
// Window: 2026-03-01 .. 2026-03-07, time_zone=gmt, datum=MLLW.
import Foundation

enum Fixtures {

''')

SF = "9414290"
parts.append(swift_str("sfHarconMetric", csv_harcon(harcon(SF, "metric")),
                       "NOAA 9414290 San Francisco -- 37 harmonic constituents, metres. name,amplitude,phase_GMT"))
dm = datums(SF, "metric")
parts.append(swift_str("sfDatumsMetric", f"MSL,{dm['MSL']}\nMLLW,{dm['MLLW']}",
                       "NOAA 9414290 datums (metres), epoch 1983-2001."))
parts.append(swift_str("sfHourlyMetric", csv_pred_h(preds(SF, "metric", "h")),
                       "NOAA 9414290 published hourly predictions, metres above MLLW, GMT."))
parts.append(swift_str("sfHiLoMetric", csv_pred_hilo(preds(SF, "metric", "hilo")),
                       "NOAA 9414290 published high/low predictions, metres above MLLW, GMT."))

parts.append(swift_str("sfHarconEnglish", csv_harcon(harcon(SF, "english")),
                       "NOAA 9414290 -- 37 harmonic constituents, FEET."))
de = datums(SF, "english")
parts.append(swift_str("sfDatumsEnglish", f"MSL,{de['MSL']}\nMLLW,{de['MLLW']}",
                       "NOAA 9414290 datums (feet)."))
parts.append(swift_str("sfHourlyEnglish", csv_pred_h(preds(SF, "english", "h")),
                       "NOAA 9414290 published hourly predictions, FEET above MLLW, GMT."))

GV = "8771450"
parts.append(swift_str("galvestonHarconMetric", csv_harcon(harcon(GV, "metric")),
                       "NOAA 8771450 Galveston Pier 21 -- diurnal regime, metres."))
dg = datums(GV, "metric")
parts.append(swift_str("galvestonDatumsMetric", f"MSL,{dg['MSL']}\nMLLW,{dg['MLLW']}",
                       "NOAA 8771450 datums (metres)."))
parts.append(swift_str("galvestonHourlyMetric", csv_pred_h(preds(GV, "metric", "h")),
                       "NOAA 8771450 published hourly predictions, metres above MLLW, GMT."))

CS, CB = "ACT1616", "1"
_ch = cur_harcon(CS, CB)
parts.append(swift_str("currentMeanFlowCMS", str(cur_mean_flow(_ch)),
                       "NOAA ACT1616 bin 1 published `majorMeanSpeed` -- the station's "
                       "non-tidal mean flow, cm/s."))
parts.append(swift_str("currentHarcon", csv_cur_harcon(_ch),
                       "NOAA ACT1616 bin 1 Pollock Rip Channel -- current constituents, "
                       "name,majorAmplitude(cm/s),majorPhaseGMT."))
parts.append(swift_str("currentPredictions", csv_cur_pred(cur_preds(CS, CB)),
                       "NOAA ACT1616 bin 1 published current predictions, 30-min, cm/s along "
                       "the major axis, GMT."))
parts.append(swift_str("currentEvents", csv_cur_events(cur_preds(CS, CB, "MAX_SLACK")),
                       "NOAA ACT1616 bin 1 published slack / max flood / max ebb events. "
                       "Time,Velocity_Major(cm/s),Type."))

parts.append("}\n")
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write("".join(parts))
n = sum(len(p) for p in parts)
print(f"wrote {OUT} ({n} bytes)")
