monsterTypeID: 7
speed: 140.0
boxWidth: 60
boxHeight: 60
damage: 6.0
health: 16.0
hitCooldown: 0.5
rotationOffset: 0
useDirectSteering: true
walkAnimationDirectory: "monsters/berserker2/walk"
dyingAnimationDirectory: "monsters/berserker2/dying"
walkFrameRate: 0.08
dyingFrameRate: 0.06
deathSounds:
  - "monster_walker_1.wav"
  - "monster_walker_2.wav"
