monsterTypeID: 5
speed: 230.0
boxWidth: 50
boxHeight: 50
damage: 5.0
health: 6.0
hitCooldown: 0.3
rotationOffset: 0
useDirectSteering: false
walkAnimationDirectory: "monsters/bird2/walk"
dyingAnimationDirectory: "monsters/bird2/dying"
walkFrameRate: 0.08
dyingFrameRate: 0.06
deathSounds:
  - "monster_avia_1.wav"
  - "monster_avia_2.wav"
mass: 1.5
