monsterTypeID: 12
speed: 150.0
boxWidth: 60
boxHeight: 60
damage: 13.0
health: 20.0
hitCooldown: 0.5
rotationOffset: 0
useDirectSteering: true
walkAnimationDirectory: "monsters/walker4/walk"
dyingAnimationDirectory: "monsters/walker4/dying"
walkFrameRate: 0.08
dyingFrameRate: 0.06
deathSounds:
  - "monster_walker_1.wav"
  - "monster_walker_2.wav"
mass: 2.5
