id: 4
name: "Minigun"
type: 4
nameLocalizations:
  en-us: "Minigun"
  ru-ru: "Миниган"
damage: 3.0
shotRange: 500.0
shotDelay: 0.05
magazineSize: 200
reloadTime: 5.0
bulletsPerShot: 1
bulletSpeed: 900.0
bulletDeviation: 50.0
maxDeviation: 100.0
penetrationPower: 1
bulletStartScale: 0.5
bulletMaxScale: 1.0
bulletScaleGrowth: 0.04
bulletTextureName: "bullet_minigun"
weaponSoundName: "weapon_minigun"
