#!/usr/bin/env python3
"""Generate StatKit's oracle corpus from the NIST StRD reference datasets.

Source: NIST/ITL Statistical Reference Datasets (StRD) — published by NIST
specifically to test the numerical accuracy of statistical software, with
certified values computed in extended precision.
  · Norris.dat  — linear least squares, 36 observations, https://www.itl.nist.gov/div898/strd/lls/data/LINKS/DATA/Norris.dat
  · Lew.dat     — univariate summary statistics, 200 observations, https://www.itl.nist.gov/div898/strd/univ/data/Lew.dat
US government work, public domain. Retrieved 2026-07-27.

Kits carry no resources, so the data is emitted as Swift literals rather than read
from disk at test time. Generating it keeps the transcription mechanical.

    python3 gen_stat_oracles.py > \
        ../Kits/Stat/StatKit/Tests/StatKitTests/OraclesNIST.swift
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
Q3 = '"""'

NORRIS_SOURCE = (
    "NIST/ITL Statistical Reference Datasets, Norris.dat (linear least squares, 36 observations, "
    "lower level of difficulty; Norris, J., NIST, \\\"Calibration of Ozone Monitors\\\"); "
    "https://www.itl.nist.gov/div898/strd/lls/data/LINKS/DATA/Norris.dat (US government work, "
    "public domain); retrieved 2026-07-27. Certified values computed by NIST in extended precision."
)
LEW_SOURCE = (
    "NIST/ITL Statistical Reference Datasets, Lew.dat (univariate summary statistics, 200 "
    "observations of steel-concrete beam deflection); "
    "https://www.itl.nist.gov/div898/strd/univ/data/Lew.dat (US government work, public domain); "
    "retrieved 2026-07-27. Certified values computed by NIST in extended precision."
)


def numbers(path, start_line, end_line):
    """1-based inclusive line range, as the .dat headers state it."""
    with open(os.path.join(HERE, path)) as fh:
        lines = fh.read().splitlines()
    return [line.split() for line in lines[start_line - 1:end_line] if line.strip()]


def certified(path, label):
    with open(os.path.join(HERE, path)) as fh:
        for line in fh:
            if label in line:
                return line.split(":")[-1].strip()
    raise SystemExit(f"{label} not found in {path}")


def main():
    # Norris: certified values on lines 31-46, data on lines 61-96 (y then x).
    norris = numbers("nist_Norris.dat", 61, 96)
    assert len(norris) == 36, len(norris)
    b0, b0sd = re.search(r"^\s+B0\s+(\S+)\s+(\S+)\s*$", open(
        os.path.join(HERE, "nist_Norris.dat")).read(), re.M).groups()
    b1, b1sd = re.search(r"^\s+B1\s+(\S+)\s+(\S+)\s*$", open(
        os.path.join(HERE, "nist_Norris.dat")).read(), re.M).groups()
    with open(os.path.join(HERE, "nist_Norris.dat")) as fh:
        text = fh.read()
    # The Norris header states these on their own lines, without a colon.
    residual_sd = re.search(r"Standard Deviation\s+([0-9.E+-]+)\s*$", text, re.M).group(1)
    r_squared = re.search(r"R-Squared\s+([0-9.E+-]+)", text).group(1)

    lew = [v[0] for v in numbers("nist_Lew.dat", 61, 260)]
    assert len(lew) == 200, len(lew)
    mean = certified("nist_Lew.dat", "ybar")
    sd = certified("nist_Lew.dat", "Sample Standard Deviation")
    autocorr = certified("nist_Lew.dat", "Sample Autocorrelation Coefficient")

    def swift_exp(value):
        """NIST writes 0.429796848199937E-03; Swift wants e-03."""
        return value.replace("E", "e")

    print(f"""// Generated by par/scratch/gen_stat_oracles.py from the NIST StRD datasets.
// Do not hand-edit: re-run the generator, so every number keeps its provenance.
// The `Oracle` type, the combined corpus and `require(_:)` live in Oracles.swift.
import Foundation

extension Oracles {{
    static let norrisSource = {Q3}
        {NORRIS_SOURCE}
        {Q3}

    static let lewSource = {Q3}
        {LEW_SOURCE}
        {Q3}

    /// Norris: y values, in file order.
    static let norrisY: [Double] = [{", ".join(y for y, _ in norris)}]

    /// Norris: x values, in file order.
    static let norrisX: [Double] = [{", ".join(x for _, x in norris)}]

    /// Lew: 200 observations, in file order.
    static let lewValues: [Double] = [{", ".join(lew)}]

    static let nistRows: [Oracle] = [
        Oracle(
            id: "nist-strd-norris",
            source: norrisSource,
            inputs: ["observations": 36],
            precision: "±1e-9 relative on the coefficients: NIST certifies 15 significant digits, and "
                + "a stable two-pass fit reproduces them to the limit of Double",
            values: [
                "intercept": {swift_exp(b0)},
                "interceptStandardDeviation": {swift_exp(b0sd)},
                "slope": {swift_exp(b1)},
                "slopeStandardDeviation": {swift_exp(b1sd)},
                "residualStandardDeviation": {swift_exp(residual_sd)},
                "rSquared": {swift_exp(r_squared)},
            ],
            tolerances: [
                "intercept": 1e-9,
                "interceptStandardDeviation": 1e-9,
                "slope": 1e-11,
                "slopeStandardDeviation": 1e-15,
                "residualStandardDeviation": 1e-9,
                "rSquared": 1e-12,
            ]
        ),
        Oracle(
            id: "nist-strd-lew",
            source: lewSource,
            inputs: ["observations": 200],
            precision: "±1e-9: NIST certifies the mean and standard deviation to 15 digits; the "
                + "autocorrelation to 15 as well",
            values: [
                "mean": {mean},
                "sampleStandardDeviation": {sd},
                "autocorrelationLag1": {autocorr},
            ],
            tolerances: [
                "mean": 1e-9,
                "sampleStandardDeviation": 1e-9,
                "autocorrelationLag1": 1e-12,
            ]
        ),
    ]
}}""")


if __name__ == "__main__":
    main()
