#!/usr/bin/env python3
"""Generate DepKit's MACRS oracle rows from the extracted IRS tables.

Source: IRS Publication 946 (2025), Appendix A, Tables A-1..A-5 (see
parse_p946_tables.py for the extraction and macrs.py for the verification).

    python3 gen_dep_oracles.py > \
        ../Kits/Depreciation/DepKit/Tests/DepKitTests/OraclesMACRS.swift
"""
import csv
import os

TABLES = [
    ("A-1", "irs946_2025_tableA1.csv", "halfYear", "Half-Year Convention", "p. 70"),
    ("A-2", "irs946_2025_tableA2_q1.csv", "midQuarterFirst",
     "Mid-Quarter Convention, Placed in Service in First Quarter", "pp. 70-71"),
    ("A-3", "irs946_2025_tableA3_q2.csv", "midQuarterSecond",
     "Mid-Quarter Convention, Placed in Service in Second Quarter", "p. 72"),
    ("A-4", "irs946_2025_tableA4_q3.csv", "midQuarterThird",
     "Mid-Quarter Convention, Placed in Service in Third Quarter", "p. 72"),
    ("A-5", "irs946_2025_tableA5_q4.csv", "midQuarterFourth",
     "Mid-Quarter Convention, Placed in Service in Fourth Quarter", "p. 73"),
]
CLASSES = ["3", "5", "7", "10", "15", "20"]
Q3 = '"""'


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    print(f"""// Generated by par/scratch/gen_dep_oracles.py from the extracted IRS tables.
// Do not hand-edit: re-run the generator, so every number keeps its provenance.
// The `Oracle` type, the combined corpus and `require(_:)` live in Oracles.swift.
import Foundation

extension Oracles {{
    /// IRS Publication 946 (2025) Appendix A, Tables A-1 through A-5: the MACRS GDS recovery
    /// percentages for every recovery period under every placed-in-service convention.
    /// Values are percent of unadjusted basis, keyed `year<n>`; tolerances are 0 because these are
    /// exact published figures and `Rounding.irsTable` reproduces them exactly.
    static let macrsRows: [Oracle] = [""")

    for name, filename, convention, subtitle, page in TABLES:
        with open(os.path.join(here, filename)) as fh:
            rows = list(csv.DictReader(l for l in fh if not l.startswith("#")))
        source = (
            f"IRS Publication 946 (2025), Appendix A, Table {name} ({subtitle}), {page}; "
            "https://www.irs.gov/pub/irs-pdf/p946.pdf (US government work, public domain); "
            "retrieved 2026-07-27. Extracted by par/scratch/parse_p946_tables.py and verified "
            "against the rules by par/scratch/macrs.py."
        )
        for klass in CLASSES:
            values = [(int(r["year"]), r[klass]) for r in rows if r[klass]]
            decimals = 3 if klass == "20" else 2
            value_lines = ", ".join(f'"year{y}": {v}' for y, v in values)
            tol_lines = ", ".join(f'"year{y}": 0' for y, _ in values)
            print(f"""        Oracle(
            id: "irs946-2025-table{name.replace('-', '')}-{klass}yr",
            source: {Q3}
                {source}
                {Q3},
            inputs: ["recoveryYears": {klass}, "decimals": {decimals}],
            precision: "exact - the published percentages carry {decimals} decimals and the "
                + "rounding-carry method reproduces them digit for digit",
            values: [{value_lines}],
            tolerances: [{tol_lines}]
        ),""")

    print("""    ]
}""")


if __name__ == "__main__":
    main()
