#!/usr/bin/env python3
"""Generate DayCountKit's ISDA oracle rows from ISDA's own workbook.

Reads isda_30_360.csv (produced by dump_isda_xls.py from
https://www.isda.org/a/mIJEE/30-360-2006ISDADefs.xls) and emits Swift.
Generating rather than hand-typing removes 22 x 10 chances to mistype a number;
the transcription is mechanical and re-runnable.

    python3 gen_daycount_oracles.py > \
        ../Kits/DayCount/DayCountKit/Tests/DayCountKitTests/OraclesISDA.swift
"""
import csv
import datetime
import os

SOURCE = (
    'ISDA, \\"Calculation examples of 30/360 and 30E/360 in the 2006 ISDA Definitions\\" '
    "(30-360-2006ISDADefs.xls, Comparison sheet), "
    "https://www.isda.org/a/mIJEE/30-360-2006ISDADefs.xls "
    "- 2006 ISDA Definitions section 4.16(f)/(g)/(h); retrieved 2026-07-27"
)
TERMINATION = "2009-02-28"  # the Comparison sheet's own termination date
Q3 = '"""'  # a Swift multiline-string delimiter, kept out of the Python literals


def ymd(iso: str) -> str:
    d = datetime.date.fromisoformat(iso)
    return f"{d.year:04d}{d.month:02d}{d.day:02d}"


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "isda_30_360.csv")) as fh:
        rows = list(csv.DictReader(fh))

    print(f"""// Generated by par/scratch/gen_daycount_oracles.py from ISDA's published workbook.
// Do not hand-edit: re-run the generator instead, so every number keeps its provenance.
// The `Oracle` type, the combined corpus and `require(_:)` live in Oracles.swift.
import Foundation

extension Oracles {{
    /// The ISDA Comparison sheet's own termination date, encoded yyyyMMdd.
    /// 4.16(h) substitutes 30 for an end date on the last day of February *unless* it is this date.
    static let terminationDate: Double = {ymd(TERMINATION)}

    static let isdaSource = {Q3}
        {SOURCE}
        {Q3}

    /// ISDA's 22 published date pairs. Expected numbers live ONLY here, tied to that source.
    static let isdaRows: [Oracle] = [""")

    for r in rows:
        start, end = ymd(r["start"]), ymd(r["end"])
        vals = {
            "days_thirty360": r["days_bond"],
            "d1_thirty360": r["d1_bond"],
            "d2_thirty360": r["d2_bond"],
            "days_thirtyE360": r["days_euro"],
            "d1_thirtyE360": r["d1_euro"],
            "d2_thirtyE360": r["d2_euro"],
            "days_thirtyE360ISDA": r["days_isda"],
            "d1_thirtyE360ISDA": r["d1_isda"],
            "d2_thirtyE360ISDA": r["d2_isda"],
            "days_actual": r["days_actual"],
        }
        value_lines = ", ".join(f'"{k}": {float(v):g}' for k, v in vals.items())
        tol_lines = ", ".join(f'"{k}": 0' for k in vals)
        print(f"""        Oracle(
            id: "isda-3060-{r['start']}-{r['end']}",
            source: isdaSource,
            inputs: ["start": {start}, "end": {end}],
            precision: "exact integers - day counts and the published D1/D2 substitutions",
            values: [{value_lines}],
            tolerances: [{tol_lines}]
        ),""")

    print("""    ]
}""")


if __name__ == "__main__":
    main()
