"""WorldConfig for the Producer torchsim.

Single source of truth: torchsim/data/game_constants.json, generated by
`npx tsx scripts/exportConstants.ts` from the TypeScript game. No gameplay
literal may live in env code — everything is read from here (the monstro
WorldConfig anti-drift rule).

Also defines GEN_KNOBS: the learnable game-hyperparameter vector theta.
Every knob is a multiplier/offset applied on top of the JSON constants,
per-env, so one batch can run many candidate game balances at once
(the substrate for CEM search over game design, Phase 4).
"""

import json
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"

with (DATA_DIR / "game_constants.json").open() as f:
    C = json.load(f)

# --- Dimensions ---
N_GENRES = len(C["genres"])                      # 6
N_ARCHETYPES = len(C["archetypes"])              # 8
N_TOPICS = len(C["trends"]["topics"])            # 10
N_EQUIP = len(C["equipment"])                    # 17
N_STAFF = len(C["staff"]["roles"])               # 6
N_NEEDS = len(C["needs"])                        # 8
N_TIERS = len(C["tiers"])                        # 5
N_WEEK_EVENTS = len(C["weekEvents"])             # 20
N_ARTIST_EVENTS = len(C["artistEvents"])         # 17
N_TRAITS = len(C["traits"])                      # 30

ROSTER_SLOTS = 12        # hard cap from labelSlots
N_CANDIDATES = 2
N_TOKENS_SLOTS = ROSTER_SLOTS + N_CANDIDATES     # 14 artist tokens

# Stat channel order (matches TS field order used everywhere here)
STATS = ["talent", "discipline", "charisma", "health", "happiness",
         "popularity", "addiction", "reputation", "selfConfidence"]
N_STATS = len(STATS)
S = {name: i for i, name in enumerate(STATS)}

GENRE_IDS = C["genres"]
ARCHETYPE_IDS = list(C["archetypes"].keys())
STAFF_ROLES = C["staff"]["roles"]
TOPIC_IDS = C["trends"]["topics"]

# --- Action space (95 ids) ---
A_END_WEEK = 0
A_SIGN0, A_SIGN1 = 1, 2
A_REJECT = 3
A_RELEASE = 4                    # +i, i in 0..11
A_TOUR = 16                      # +i
A_REHAB = 28                     # +i
A_FIRE = 40                      # +i
A_FULFILL = 52                   # +i
A_HIRE = 64                      # +r, r in 0..5
A_FIRE_STAFF = 70                # +r
A_BUY_EQUIP = 76                 # +e, e in 0..16
A_UPGRADE_STUDIO = 93
A_UPGRADE_LABEL = 94
N_ACTIONS = 95

MAX_ACTIONS_PER_WEEK = 16        # mirrors scripts/headless.ts
MAX_REJECTS_PER_WEEK = 16        # effectively uncapped within the action cap
                                 # (TS driver has no reject cap — parity)
MAX_WEEKS = 520                  # timeout beyond the 480-week victory horizon

# --- Learnable game-hyperparameter knobs (theta) ---
# name -> (default, lo, hi). Applied per-env in env_producer.
GEN_KNOBS = {
    "pay_mult_meme":    (1.0, 0.2, 5.0),   # tier payRate multipliers
    "pay_mult_normal":  (1.0, 0.2, 5.0),
    "pay_mult_hit":     (1.0, 0.2, 5.0),
    "pay_mult_cult":    (1.0, 0.2, 5.0),
    "release_cost_mult":(1.0, 0.3, 3.0),
    "tour_rev_mult":    (1.0, 0.3, 3.0),
    "tour_cost_mult":   (1.0, 0.3, 3.0),
    "salary_mult":      (1.0, 0.3, 3.0),
    "upgrade_cost_mult":(1.0, 0.3, 3.0),
    "equip_cost_mult":  (1.0, 0.3, 3.0),
    "start_money_mult": (1.0, 0.25, 5.0),
    "week_event_chance":(C["weekly"]["weekEventChance"], 0.0, 0.8),
    "artist_event_chance":(C["weekly"]["artistEventChance"], 0.0, 0.9),
    "need_chance":      (C["weekly"]["needChance"], 0.0, 0.8),
    "luck_spread_mult": (1.0, 0.25, 3.0),
    "bankruptcy_floor": (float(C["winLose"]["bankruptcyBelow"]), -200000.0, -10000.0),
    # найгостріший інструмент проти release-machine-gun експлойту, який знайшов
    # RL-агент: множник токен-нагороди робить масові релізи самообмежними
    "token_reward_mult": (1.0, 0.1, 1.5),
    # раунд-2 агент виграє через НЕОЦІНЕНИЙ вимір — вихід фанів з релізу;
    # цей ноб дає CEM цінник на саму валюту перемоги. НЕ входить у obs
    # (прихований вимір складності; v2-політика тренована на 17 нобах)
    "fan_rate_mult": (1.0, 0.1, 2.0),
}
KNOB_NAMES = list(GEN_KNOBS.keys())
N_KNOBS = len(KNOB_NAMES)
# knobs the theta-aware policy OBSERVES (frozen at the v2 training set of 17)
OBS_KNOB_NAMES = [k for k in KNOB_NAMES if k != "fan_rate_mult"]
N_OBS_KNOBS = len(OBS_KNOB_NAMES)

# --- Observation normalizers (train == deploy; the desertion-bug rule) ---
OBS = {
    "money_log_div": 8.0,        # sign(m)*log1p(|m|/1e3)/8, clamp +-1.25
    "money_lin_div": 50000.0,    # bankruptcy-scale linear term, clamp +-2
    "fans_log_max": 100_000_000, # log1p(f)/log1p(1e8), clamp [0, 1.2]
    "stat_center": 50.0, "stat_div": 40.0,
    "afford_clamp": 2.0,         # clamp(log10(cost/max(money,1)), -2, 2)/2
    "tokens_div": 8.0,
    "week_div": 480.0,
}

MASK_NEG = -1e4   # fp16/ANE-safe mask constant (monstro war story). NEVER finfo.min.
